// =====================================================================
// chat.js — แชตของ Group / Trip (ข้อความ + รูป) แบบ Realtime
// =====================================================================
let chatRoom=null,chatMsgs=[],chatUnread={},chatChannel=null,chatLoadingOlder=false,chatHasMore=false,chatFile=null;
const chatProfiles=new Map(),chatUrls=new Map();
function roomKey(t,id){return t+':'+id}
function chatRooms(){const out=[];cache.trips.filter(t=>cache.roles[t.id]).forEach(t=>out.push({type:'trip',id:t.id,name:t.name,sub:t.trip_no,closed:t.status==='closed',icon:'🧳'}));cache.groups.forEach(g=>out.push({type:'group',id:g.id,name:g.name,sub:'Group',closed:false,icon:'👥'}));out.forEach(r=>{const u=chatUnread[roomKey(r.type,r.id)]||{};r.unread=u.n||0;r.last=u.last||''});return out.sort((a,b)=>String(b.last).localeCompare(String(a.last))||(a.type===b.type?0:a.type==='trip'?-1:1))}
async function loadChatUnread(){try{const {data,error}=await sb.rpc('chat_unread_counts');if(error)throw error;chatUnread={};(data||[]).forEach(r=>chatUnread[roomKey(r.room_type,r.room_id)]={n:Number(r.unread||0),last:r.last_at||''})}catch(x){console.warn('chat unread',x)}renderChatBadges();if($('chat')?.classList.contains('active'))renderChatRooms()}
function renderChatBadges(){const n=Object.values(chatUnread).reduce((a,x)=>a+(x.n||0),0);document.querySelectorAll('.chatCount').forEach(el=>{el.textContent=n>99?'99+':n;el.classList.toggle('hide',!n)})}
function renderChatPage(){renderChatRooms();if(!chatRoom){const first=chatRooms().find(r=>r.type==='trip'&&r.id===curTripId);if(first&&window.innerWidth>950)openChatRoom(first.type,first.id)}}
function renderChatRooms(){const box=$('chatRooms');if(!box)return;const rooms=chatRooms();box.innerHTML=rooms.map(r=>`<button class="chatroom ${chatRoom&&chatRoom.id===r.id?'active':''}" onclick="openChatRoom('${r.type}','${r.id}')"><span class="ricon">${r.icon}</span><span class="rname"><b>${esc(r.name)}</b><small>${esc(r.sub)}${r.closed?' · 🔒 ปิดแล้ว':''}</small></span>${r.unread?`<span class="rcount">${r.unread>99?'99+':r.unread}</span>`:''}</button>`).join('')||'<div class="empty">ยังไม่มีห้องแชต<br><span class="mini">เข้าร่วม Group หรือ Trip ก่อน</span></div>'}
function openChatFor(type,id){go('chat');openChatRoom(type,id)}
async function openChatRoom(type,id){const r=chatRooms().find(x=>x.type===type&&x.id===id);if(!r)return;chatRoom=r;chatMsgs=[];chatFile=null;$('chat').classList.add('inroom');$('chatHead').innerHTML=`<button class="btn sm secondary backbtn" onclick="closeChatRoom()">‹</button><span class="ricon">${r.icon}</span><div style="min-width:0;flex:1"><b>${esc(r.name)}</b><div class="mini muted">${esc(r.sub)}${r.closed?' · 🔒 Trip ปิดแล้ว อ่านได้อย่างเดียว':''}</div></div>`;$('chatComposer').classList.toggle('hide',r.closed);$('chatClosedNote').classList.toggle('hide',!r.closed);$('chatMsgs').innerHTML='<div class="empty">กำลังโหลด...</div>';renderChatRooms();await loadChatMessages();markChatRead()}
function closeChatRoom(){chatRoom=null;$('chat').classList.remove('inroom');renderChatRooms()}
async function loadChatMessages(before){if(!chatRoom)return;const room=chatRoom;let q=sb.from('chat_messages').select('*').eq('room_type',room.type).eq('room_id',room.id).order('created_at',{ascending:false}).limit(50);if(before)q=q.lt('created_at',before);const {data,error}=await q;if(chatRoom!==room)return;if(error){$('chatMsgs').innerHTML=`<div class="warnbox">${esc(friendlyError(error))}</div>`;return}const rows=(data||[]).reverse();chatHasMore=(data||[]).length===50;chatMsgs=before?[...rows,...chatMsgs]:rows;await ensureChatProfiles(rows.map(m=>m.sender));renderChatMessages(!before)}
async function loadOlderChat(){if(chatLoadingOlder||!chatMsgs.length)return;chatLoadingOlder=true;const box=$('chatMsgs'),h=box.scrollHeight;await loadChatMessages(chatMsgs[0].created_at);box.scrollTop=box.scrollHeight-h;chatLoadingOlder=false}
async function ensureChatProfiles(ids){const need=[...new Set(ids)].filter(id=>id&&!chatProfiles.has(id)&&!cache.members.some(m=>m.id===id));cache.members.forEach(m=>chatProfiles.set(m.id,m));if(!need.length)return;try{const {data}=await sb.from('profiles').select('id,full_name,nickname').in('id',need);(data||[]).forEach(p=>chatProfiles.set(p.id,p))}catch(_){}}
function chatName(uid){return displayName(chatProfiles.get(uid)||cache.members.find(m=>m.id===uid)||{id:uid})}
function linkify(s){return esc(s).replace(/(https?:\/\/[^\s<]+)/g,'<a href="$1" target="_blank" rel="noopener">$1</a>').replace(/\n/g,'<br>')}
function chatTime(d){const x=new Date(d);return x.toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'})}
function chatDay(d){return new Date(d).toLocaleDateString('th-TH',{weekday:'short',day:'numeric',month:'short',year:'numeric'})}
function canDeleteChat(m){if(m.deleted_at||!chatRoom)return false;if(m.sender===currentUser.id)return true;return chatRoom.type==='group'?['owner','admin'].includes(cache.groups.find(g=>g.id===chatRoom.id)?.role):canAdmin(chatRoom.id)}
function renderChatMessages(scrollBottom){const box=$('chatMsgs');if(!box)return;const atBottom=box.scrollHeight-box.scrollTop-box.clientHeight<80;let lastDay='',lastSender='';box.innerHTML=(chatHasMore?'<div style="text-align:center"><button class="btn sm secondary" onclick="loadOlderChat()">โหลดข้อความก่อนหน้า</button></div>':'')+chatMsgs.map(m=>{const day=chatDay(m.created_at);const mine=m.sender===currentUser.id;let h='';if(day!==lastDay){h+=`<div class="chatday">${esc(day)}</div>`;lastDay=day;lastSender=''}const showName=!mine&&m.sender!==lastSender;lastSender=m.sender;h+=`<div class="msg ${mine?'mine':''}">${showName?`<div class="mname">${esc(chatName(m.sender))}</div>`:''}<div class="bubble">${m.deleted_at?'<i class="muted">ข้อความถูกลบ</i>':`${m.image_path?`<a class="chatimg" data-path="${esc(m.image_path)}" target="_blank" rel="noopener"><img alt="" loading="lazy"></a>`:''}${m.body?`<div>${linkify(m.body)}</div>`:''}`}<span class="mtime">${chatTime(m.created_at)}${canDeleteChat(m)?` <button class="mdel" title="ลบ" onclick="deleteChatMsg('${m.id}')">🗑</button>`:''}</span></div></div>`;return h}).join('')||'<div class="empty">ยังไม่มีข้อความ เริ่มคุยกันเลย 👋</div>';hydrateChatImages();if(scrollBottom||atBottom)box.scrollTop=box.scrollHeight}
async function hydrateChatImages(){const els=[...document.querySelectorAll('#chatMsgs .chatimg')];const need=[...new Set(els.map(a=>a.dataset.path).filter(p=>!chatUrls.has(p)))];if(need.length){try{const {data}=await sb.storage.from('chat-images').createSignedUrls(need,3600);(data||[]).forEach(x=>{if(x.signedUrl)chatUrls.set(x.path,x.signedUrl)})}catch(_){}}els.forEach(a=>{const u=chatUrls.get(a.dataset.path);if(u){a.href=u;const img=a.querySelector('img');if(img&&!img.src){img.onload=()=>{const b=$('chatMsgs');if(b&&b.scrollHeight-b.scrollTop-b.clientHeight<400)b.scrollTop=b.scrollHeight};img.src=u}}})}
function onChatFile(input){const f=input.files[0];input.value='';if(!f)return;if(!/^image\//.test(f.type))return alert('แนบได้เฉพาะรูปภาพ');chatFile=f;$('chatFileName').innerHTML=`🖼️ ${esc(f.name)} <button class="btn sm ghost" onclick="chatFile=null;$('chatFileName').innerHTML=''">✕</button>`}
function chatKey(e){if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&window.innerWidth>950){e.preventDefault();sendChat()}}
async function sendChat(){if(!chatRoom||chatRoom.closed)return;const ta=$('chatInput'),btn=$('chatSend');const body=ta.value.trim();if(!body&&!chatFile)return;if(body.length>2000)return alert('ข้อความยาวเกิน 2,000 ตัวอักษร');btn.disabled=true;let path=null;try{if(chatFile){let f=chatFile;try{f=await compressImage(chatFile,1600,.8)}catch(_){}if(f.size>5*1024*1024)throw new Error('รูปใหญ่เกิน 5 MB');path=`${chatRoom.type}/${chatRoom.id}/${currentUser.id}/${uniqId()}.${/png$/.test(f.type)?'png':/webp$/.test(f.type)?'webp':/gif$/.test(f.type)?'gif':'jpg'}`;const {error:ue}=await sb.storage.from('chat-images').upload(path,f,{contentType:f.type||'image/jpeg',upsert:false});if(ue)throw ue}const {data,error}=await sb.from('chat_messages').insert({room_type:chatRoom.type,room_id:chatRoom.id,sender:currentUser.id,body:body||null,image_path:path}).select().single();if(error){if(path)await sb.storage.from('chat-images').remove([path]);throw error}ta.value='';chatFile=null;$('chatFileName').innerHTML='';upsertChatMsg(data);renderChatMessages(true);markChatRead()}catch(e){err(e)}finally{btn.disabled=false;ta.focus()}}
async function deleteChatMsg(id){if(!confirm('ลบข้อความนี้?'))return;try{const {data,error}=await sb.rpc('delete_chat_message',{p_id:id});if(error)throw error;if(data)await sb.storage.from('chat-images').remove([data]);const m=chatMsgs.find(x=>x.id===id);if(m){m.deleted_at=new Date().toISOString();m.body=null;m.image_path=null}renderChatMessages()}catch(e){err(e)}}
function upsertChatMsg(m){const i=chatMsgs.findIndex(x=>x.id===m.id);if(i>=0)chatMsgs[i]=m;else{chatMsgs.push(m);chatMsgs.sort((a,b)=>String(a.created_at).localeCompare(String(b.created_at)))}}
async function markChatRead(){if(!chatRoom)return;const k=roomKey(chatRoom.type,chatRoom.id);if(chatUnread[k])chatUnread[k].n=0;renderChatBadges();renderChatRooms();try{await sb.rpc('mark_chat_read',{p_type:chatRoom.type,p_id:chatRoom.id})}catch(_){}}
function subscribeChat(){if(chatChannel||!sb?.channel)return;chatChannel=sb.channel('chat-all').on('postgres_changes',{event:'*',schema:'public',table:'chat_messages'},p=>onChatChange(p)).subscribe()}
function unsubscribeChat(){if(chatChannel){try{sb.removeChannel(chatChannel)}catch(_){}chatChannel=null}chatRoom=null;chatMsgs=[];chatUnread={}}
async function onChatChange(p){const m=p.new;if(!m||!m.id)return;const k=roomKey(m.room_type,m.room_id);const viewing=chatRoom&&k===roomKey(chatRoom.type,chatRoom.id)&&$('chat').classList.contains('active')&&document.visibilityState==='visible';if(chatRoom&&k===roomKey(chatRoom.type,chatRoom.id)){await ensureChatProfiles([m.sender]);upsertChatMsg(m);renderChatMessages()}if(p.eventType==='INSERT'){chatUnread[k]={n:(chatUnread[k]?.n||0)+(m.sender!==currentUser.id&&!viewing?1:0),last:m.created_at};if(viewing)markChatRead();else if(m.sender!==currentUser.id){renderChatBadges();renderChatRooms();await ensureChatProfiles([m.sender]);const r=chatRooms().find(x=>roomKey(x.type,x.id)===k);toast(`💬 ${chatName(m.sender)}${r?' · '+r.name:''}: ${m.body?String(m.body).slice(0,40):'📷 รูปภาพ'}`)}}}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&chatRoom&&$('chat')?.classList.contains('active'))markChatRead()});
