// dashboard.js — Dashboard ของ Trip ปัจจุบัน และกราฟ
function renderDashboard(){const t=curTrip();const hero=$('dashHero');const total=cache.expenses.reduce((a,e)=>a+Number(e.amount||0),0);
  if(!t){hero.innerHTML=`<div class="card hero empty"><h2 style="margin:0 0 6px">ยินดีต้อนรับสู่ TripExpense 👋</h2><div class="muted">เริ่มจากสร้าง Group และ Trip แรก หรือใส่ Group Code ที่ได้จากเพื่อน</div><br><div class="row" style="justify-content:center"><button class="btn" onclick="openTripForm()">＋ สร้าง Trip</button><button class="btn secondary" onclick="go('groups')">👥 เข้าร่วม Group</button></div></div>`;['mTotal','mMembers','mExp','mRemain'].forEach(id=>$(id).textContent='-');$('dashBudget').innerHTML='';$('dashSettle').innerHTML='<div class="empty">-</div>';$('dashExpenses').innerHTML='<div class="empty">-</div>';return}
  const st=tripStatus(t),days=tripDates(t);let dayInfo='';if(st.key==='traveling')dayInfo=`วันที่ ${days.indexOf(today())+1} จาก ${days.length} วัน`;else if(st.key==='planning'&&t.start_date){const n=Math.round((new Date(t.start_date+'T00:00:00')-new Date(today()+'T00:00:00'))/86400000);dayInfo=`อีก ${n} วันจะออกเดินทาง`}
  hero.innerHTML=`<div class="card hero"><div class="row" style="align-items:flex-start"><div style="min-width:0;flex:1"><div class="muted">${esc(t.trip_no)}</div><h2 style="margin:2px 0 6px">${esc(t.name)}</h2><div class="muted">📍 ${esc(t.destination||'ยังไม่ระบุสถานที่')} · 📅 ${esc(tripRangeText(t))}</div>${dayInfo?`<div class="mini" style="margin-top:4px"><b>${dayInfo}</b></div>`:''}</div><div class="row" style="gap:6px"><span class="pill st-${st.key}">${st.label}</span><span class="badge">${devViewId?'👁 Developer':roleName(myRole())}</span></div></div><div class="row" style="margin-top:12px"><button class="btn sm secondary" onclick="openTripDetail('${t.id}')">รายละเอียด / สมาชิก</button><button class="btn sm w" onclick="openExpenseForm()">＋ ค่าใช้จ่าย</button>${canAdmin()?`<button class="btn sm secondary" onclick="closeTrip('${t.id}')">🔒 ปิด Trip</button>`:''}</div></div>`;
  $('mTotal').textContent=money(total);$('mMembers').textContent=cache.tripMembers.length;$('mExp').textContent=cache.expenses.length;const bs=budgetStats(t.id);$('mRemain').textContent=bs.b?money(bs.remaining):'ยังไม่ตั้ง';$('mRemain').className=bs.b&&bs.remaining<0?'dangerText':'';
  renderDashboardBudget();renderSettlement(t.id,'dashSettle',true);
  $('dashExpenses').innerHTML=cache.expenses.slice(0,6).map(e=>`<div class="listitem"><b>${esc(e.detail||catName(e.category))}</b><span style="float:right">${money(e.amount)}</span><div class="muted">${esc(e.expense_date)} · ${esc(catName(e.category))} · จ่ายโดย ${esc(payerName(e.payer_id))}</div></div>`).join('')||'<div class="empty">ยังไม่มีรายการ</div>'}
function renderDashboardBudget(){const el=$('dashBudget');if(!el)return;if(!curTripId){el.innerHTML='';return}const r=budgetStats(curTripId);if(!r.b){el.innerHTML=budgetWarning()+`<div class="empty">ยังไม่ได้ตั้งงบประมาณ${canAdmin()?`<br><br><button class="btn sm" onclick="openBudgetForm()">ตั้งงบประมาณ</button>`:''}</div>`;return}el.innerHTML=`<div class="row"><b>${money(r.spent)} / ${money(r.budget)}</b><div class="spacer"></div><span class="badge">${r.status==='over'?'เกินงบ':r.status==='alert'?'ใกล้ถึงงบ':'อยู่ในงบ'}</span></div><div class="summarybar" style="margin-top:8px"><i style="width:${Math.min(100,r.pct)}%;${r.status==='over'?'background:var(--danger)':''}"></i></div><div class="muted" style="margin-top:6px">ใช้ไป ${r.pct.toFixed(1)}% · คงเหลือ ${money(r.remaining)} · Forecast ${money(r.forecast)}</div>`}
function renderCharts(){const c=catTotals(cache.expenses);const max=Math.max(1,...Object.values(c));const keys=[...Object.keys(DEFAULT_CATS),...Object.keys(c).filter(k=>!DEFAULT_CATS[k]).sort((a,b)=>c[b]-c[a])];$('categoryChart').innerHTML=keys.map(k=>`<div class="barrow"><span title="${esc(catName(k))}">${esc(catName(k))}</span><div class="bartrack"><i style="width:${(c[k]||0)/max*100}%"></i></div><b>${money(c[k]||0)}</b></div>`).join('')||'<div class="empty">ยังไม่มีข้อมูล</div>';const p={};cache.expenses.forEach(e=>p[e.payer_id]=(p[e.payer_id]||0)+Number(e.amount));const pm=new Map(cache.members.map(x=>[x.id,x.full_name]));const vals=Object.entries(p).sort((a,b)=>b[1]-a[1]);const mx=Math.max(1,...vals.map(x=>x[1]));$('payerChart').innerHTML=vals.map(([id,v])=>`<div class="barrow"><span>${esc(payerName(id))}</span><div class="bartrack"><i style="width:${v/mx*100}%"></i></div><b>${money(v)}</b></div>`).join('')||'<div class="empty">ยังไม่มีข้อมูล</div>';const byDay={};cache.expenses.forEach(e=>byDay[e.expense_date]=(byDay[e.expense_date]||0)+Number(e.amount||0));const dv=Object.entries(byDay).sort((a,b)=>a[0].localeCompare(b[0]));const dx=Math.max(1,...dv.map(x=>x[1]));$('tripExpenseChart').innerHTML=dv.map(([d,v])=>`<div class="barrow"><span>${esc(thaiDate(d))}</span><div class="bartrack"><i style="width:${v/dx*100}%"></i></div><b>${money(v)}</b></div>`).join('')||'<div class="empty">ยังไม่มีข้อมูล</div>'}
