// =====================================================================
// dashboard.js — หน้าหลัก (V17): ทักทาย, แบนเนอร์ Trip, รวมค่าใช้จ่าย/งบ, โดนัทหมวด, ทางลัด
// =====================================================================
function catParts(list){const c=catTotals(list);return Object.entries(c).filter(([,v])=>v>0.004).sort((a,b)=>b[1]-a[1]).map(([k,v])=>({k,v,name:catName(k),color:catMeta(k).color}))}
function renderDashboard(){const box=$('homeBox');if(!box)return;const t=curTrip();const hello=`<div class="hello"><div style="min-width:0;flex:1"><h2>สวัสดี, ${esc(displayName(me||{id:currentUser?.id}))} 👋</h2><div class="muted">ทริปครั้งนี้...เก็บไว้ในความทรงจำ</div></div></div>`;
  if(!t){box.innerHTML=hello+`<div class="card hero empty"><div class="bigicon">${lineIcon('trips')}</div><h3 style="margin:6px 0">เริ่มทริปแรกของคุณ</h3><div class="muted">สร้าง Trip ใหม่ หรือใส่ Code ที่ได้จากเพื่อน</div><br><div class="row" style="justify-content:center"><button class="btn" onclick="openTripForm()">＋ สร้าง Trip</button><button class="btn secondary" onclick="openJoinCode()">🔑 ใส่ Code</button></div></div>`;return}
  const st=tripStatus(t),days=tripDates(t);let dayInfo='';if(st.key==='traveling')dayInfo=LANG==='en'?`Day ${days.indexOf(today())+1} of ${days.length}`:`วันที่ ${days.indexOf(today())+1} จาก ${days.length} วัน`;else if(st.key==='planning'&&t.start_date){const n=Math.round((new Date(t.start_date+'T00:00:00')-new Date(today()+'T00:00:00'))/86400000);dayInfo=LANG==='en'?`${n} days until departure`:`อีก ${n} วันจะออกเดินทาง`}
  const total=cache.expenses.reduce((a,e)=>a+netOf(e),0),bs=budgetStats(t.id),parts=catParts(cache.expenses);const pct=bs.b?Math.min(100,bs.pct):0;
  const closed=isClosed(t);
  box.innerHTML=hello+`<div class="tripcard" onclick="openTripDetail('${t.id}')"><div class="tc-photo"${t.photo_path?` data-av="${esc(t.photo_path)}"`:''}><span class="pill st-${st.key}">${st.label}</span>${canAdmin()?`<button class="iconbtn light" title="เปลี่ยนรูปปก" onclick="event.stopPropagation();changeTripPhoto('${t.id}')">${lineIcon('camera')}</button>`:''}</div><div class="tc-body"><h2>${esc(t.name)}</h2><div class="tc-meta">${esc(fmtRange(t))}${t.destination?' · 📍 '+esc(t.destination):''}</div>${dayInfo?`<div class="tc-day">${dayInfo}</div>`:''}</div></div>
  ${closed?`<div class="card doneSummary"><div class="bigicon">${lineIcon('settle')}</div><h3 style="margin:6px 0">ทริปนี้จบแล้ว</h3><div class="muted">${LANG==='en'?`This trip cost <b>${money(total)}</b> over ${days.length||'-'} days${cache.tripMembers.length?` with ${cache.tripMembers.length} people`:''}`:`ทริปนี้ใช้ไปทั้งหมด <b>${money(total)}</b> ใน ${days.length||'-'} วัน${cache.tripMembers.length?` กับเพื่อน ${cache.tripMembers.length} คน`:''}`}</div><div class="row" style="justify-content:center;margin-top:12px"><button class="btn" onclick="openSummary('overview')">📊 ดูสรุปทั้งหมด</button><button class="btn secondary" onclick="go('history')">📔 ประวัติการเดินทาง</button></div></div>`:''}
  <div class="grid2 statcards"><div class="card statcard" onclick="openSummary('list')"><span class="sicon" style="--c:#3b82f6">${lineIcon('expense')}</span><div class="muted">รวมค่าใช้จ่าย</div><b>${money(total)}</b><div class="mini muted">จากทั้งหมด ${cache.expenses.length} รายการ</div></div><div class="card statcard" onclick="go('budget')"><span class="sicon" style="--c:#10b981">${lineIcon('budget')}</span><div class="muted">งบประมาณ</div>${bs.b?`<b>${money(bs.budget)}</b><div class="summarybar" style="margin-top:6px"><i style="width:${pct}%;${bs.status==='over'?'background:var(--danger)':bs.status==='alert'?'background:#f59e0b':''}"></i></div><div class="mini muted" style="text-align:right">${bs.pct.toFixed(0)}%</div>`:`<b class="muted">ยังไม่ตั้ง</b>${canAdmin()?'<div class="mini" style="color:var(--brand)">แตะเพื่อตั้งงบ</div>':''}`}</div></div>
  <div class="card"><div class="section"><h3>หมวดหมู่ค่าใช้จ่าย</h3><div class="spacer"></div><button class="btn sm ghost" onclick="openSummary('category')">ดูทั้งหมด ›</button></div>${parts.length?`<div class="donutwrap">${donutSvg(parts,total)}<div class="legend">${parts.slice(0,6).map(p=>`<div class="lg"><i style="background:${p.color}"></i><span>${esc(p.name)}</span><b>${total?Math.round(p.v/total*100):0}%</b></div>`).join('')}</div></div>`:'<div class="empty">ยังไม่มีค่าใช้จ่าย<br><br><button class="btn w" onclick="openExpenseForm()">＋ เพิ่มค่าใช้จ่ายแรก</button></div>'}</div>
  <div class="shortcuts"><button onclick="openChatFor('trip','${t.id}')"><span>${lineIcon('chat')}</span>แชต</button><button onclick="go('schedule')"><span>${lineIcon('schedule')}</span>Schedule</button><button onclick="go('documents')"><span>${lineIcon('documents')}</span>เอกสาร</button><button onclick="openSummary('overview',true)"><span>${lineIcon('expense')}</span>Settlement</button><button onclick="openTripDetail('${t.id}','members')"><span>${lineIcon('groups')}</span>สมาชิก</button>${closed?"":`<button onclick="openInviteModal('trip','${t.id}')"><span>${lineIcon('invite')}</span>เชิญ</button>`}</div>
  <div class="card"><div class="section"><h3>💸 ยอดค้างชำระคืน</h3><div class="spacer"></div><button class="btn sm ghost" onclick="openSummary('overview',true)">Settlement ›</button></div><div id="dashSettle"></div></div>
  <div class="card"><div class="section"><h3>ค่าใช้จ่ายล่าสุด</h3><div class="spacer"></div><button class="btn sm ghost" onclick="openSummary('list')">ดูทั้งหมด ›</button></div>${cache.expenses.slice(0,5).map(expenseRowHtml).join('')||'<div class="empty">ยังไม่มีรายการ</div>'}</div>`;
  renderSettlement(t.id,'dashSettle',true);hydrateMedia(box)}
function renderDashboardBudget(){}
