// =====================================================================
// developer.js — Developer Console (ดูได้อย่างเดียว, ฐานข้อมูลบังคับสิทธิ์)
// =====================================================================
let devData=null;
async function renderDeveloper(){const box=$('devBox');if(!box)return;if(!isDev){box.innerHTML='<div class="card empty">เฉพาะ Developer</div>';return}box.innerHTML='<div class="empty">กำลังโหลด...</div>';try{const {data,error}=await sb.rpc('dev_overview');if(error)throw error;devData=data;drawDeveloper()}catch(e){box.innerHTML=`<div class="warnbox">${esc(friendlyError(e))}</div>`}}
function drawDeveloper(){const d=devData;if(!d)return;const s=d.stats||{};const q=($('devSearch')?.value||'').trim().toLowerCase();const match=(...v)=>!q||v.some(x=>String(x||'').toLowerCase().includes(q));const trips=(d.trips||[]).filter(t=>match(t.trip_no,t.name,t.group_name));const groups=(d.groups||[]).filter(g=>match(g.name,g.code,g.owner_name));
  $('devBox').innerHTML=`<div class="grid4"><div class="card metric"><div class="muted">ผู้ใช้</div><b>${s.users??0}</b></div><div class="card metric"><div class="muted">Groups</div><b>${s.groups??0}</b></div><div class="card metric"><div class="muted">Trips (ใช้งาน/ทั้งหมด)</div><b>${s.active_trips??0} / ${s.trips??0}</b></div><div class="card metric"><div class="muted">ค่าใช้จ่ายทั้งระบบ</div><b>${money(s.total)}</b><div class="mini muted">${s.expenses??0} รายการ</div></div></div><br><div class="card"><div class="row filterbar"><input id="devSearch" placeholder="🔍 ค้นหา Trip / Group / Code" value="${esc(q)}" oninput="drawDeveloper();const i=$('devSearch');i.focus();i.setSelectionRange(i.value.length,i.value.length)" style="flex:1;min-width:200px"><button class="btn sm secondary" onclick="renderDeveloper()">↻ โหลดใหม่</button></div></div><br><div class="card"><div class="section"><h3>Trips (${trips.length})</h3></div><div class="tablewrap"><table class="table"><thead><tr><th>Trip</th><th>Group</th><th>สถานะ</th><th>วันที่</th><th>สมาชิก</th><th>ค่าใช้จ่าย</th><th></th></tr></thead><tbody>${trips.map(t=>{const st=tripStatus(t);return `<tr><td><b>${esc(t.trip_no)}</b><div class="muted">${esc(t.name)}</div></td><td>${esc(t.group_name||'-')}</td><td><span class="pill st-${st.key}">${st.label}</span></td><td>${esc(t.start_date||'-')}${t.end_date?' → '+esc(t.end_date):''}</td><td>${t.members}</td><td>${money(t.total)}<div class="muted">${t.expense_count} รายการ</div></td><td><button class="btn sm secondary" onclick="devViewTrip('${t.id}')">👁 ดู</button></td></tr>`}).join('')||'<tr><td colspan="7" class="empty">ไม่พบ</td></tr>'}</tbody></table></div></div><br><div class="card"><div class="section"><h3>Groups (${groups.length})</h3></div><div class="tablewrap"><table class="table"><thead><tr><th>Group</th><th>Code</th><th>Owner</th><th>สมาชิก</th><th>Trips</th><th>สร้างเมื่อ</th></tr></thead><tbody>${groups.map(g=>`<tr><td><b>${esc(g.name)}</b></td><td>${esc(g.code)}</td><td>${esc(g.owner_name||'-')}</td><td>${g.members}</td><td>${g.trips}</td><td>${esc(String(g.created_at||'').slice(0,10))}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">ไม่พบ</td></tr>'}</tbody></table></div></div><div class="mini muted" style="margin-top:10px">Developer ดูข้อมูลได้อย่างเดียว แก้ไขไม่ได้ และไม่เห็นเอกสารที่ผู้ใช้ตั้งเป็น "เฉพาะฉัน" รวมถึงข้อมูลติดต่อส่วนตัว</div>`}
async function devViewTrip(tid){if(!isDev)return;devViewId=tid;curTripId=tid;calInit=false;await render();go('dashboard')}
async function exitDevView(){devViewId=null;curTripId=null;calInit=false;await render();go('developer')}
