// documents.js — เอกสารการเดินทาง
const DOC_TYPES={hotel:['🏨','จองโรงแรม'],flight_ticket:['✈️','ตั๋วเครื่องบิน'],flight_booking:['🧾','เอกสารจองเที่ยวบิน'],ground:['🚆','ตั๋วรถไฟ/รถ/เรือ'],car_rental:['🚗','รถเช่า'],insurance:['🛡️','ประกันเดินทาง'],passport_visa:['🛂','วีซ่า/พาสปอร์ต'],other:['📁','อื่นๆ']};
function docTypeName(v){return DOC_TYPES[v]?.[1]||v||'อื่นๆ'}
function docTypeIcon(v){return DOC_TYPES[v]?.[0]||'📎'}
function docTypeKey(s){s=String(s||'').trim().replace(/\s+/g,' ');if(!s)return 'other';const hit=Object.entries(DOC_TYPES).find(([k,v])=>v[1]===s||k===s);return hit?hit[0]:s.slice(0,40)}
function docFiles(did){return cache.docFiles.filter(f=>f.document_id===did)}
function docsForSchedule(sid){return cache.documents.filter(d=>d.schedule_id===sid)}
function renderDocFilters(){const ty=$('docType'),curT=ty.value;const custom=[...new Set(cache.documents.map(d=>d.doc_type).filter(v=>v&&!DOC_TYPES[v]))];ty.innerHTML='<option value="all">ทุกประเภท</option>'+[...Object.keys(DOC_TYPES),...custom].map(k=>`<option value="${esc(k)}">${docTypeIcon(k)} ${esc(docTypeName(k))}</option>`).join('');ty.value=[...ty.options].some(o=>o.value===curT)?curT:'all'}
function docCardHtml(d){const t=tripById(d.trip_id),files=docFiles(d.id),mine=d.created_by===currentUser?.id&&canWrite(),s=d.schedule_id?cache.schedules.find(x=>x.id===d.schedule_id):null;return `<div class="card doccard"><div class="row" style="flex-wrap:nowrap"><span class="docicon">${docTypeIcon(d.doc_type)}</span><div style="min-width:0;flex:1"><b>${esc(d.title)}</b><div class="muted">${esc(docTypeName(d.doc_type))} · ${esc(t?.trip_no||'-')}</div></div><span class="pill ${d.visibility==='private'?'private':''}">${d.visibility==='private'?'🔒 เฉพาะฉัน':'👥 แชร์'}</span></div>${d.reference_no?`<div class="mini" style="margin-top:8px">เลขที่การจอง: <b>${esc(d.reference_no)}</b></div>`:''}${d.doc_date?`<div class="mini">วันที่: ${esc(d.doc_date)}</div>`:''}${s?`<div class="mini">🔗 ${esc(s.schedule_date)} · ${esc(s.activity||s.hotel_name||'')}</div>`:''}<div class="thumbs small" id="dthumb-${d.id}">${files.length?`<span class="muted mini">กำลังโหลด ${files.length} ไฟล์...</span>`:'<span class="muted mini">ไม่มีไฟล์แนบ</span>'}</div><div class="row docactions"><button class="btn sm" onclick="openDocViewer('${d.id}')">เปิด</button>${mine?`<button class="btn sm secondary" onclick="openDocForm('${d.id}')">แก้ไข</button><button class="btn sm danger" onclick="deleteDoc('${d.id}')">ลบ</button>`:'<span class="muted mini">เพิ่มโดยสมาชิกคนอื่น</span>'}</div></div>`}
let docThumbToken=0;
async function loadDocThumbs(list){const my=++docThumbToken;const files=list.flatMap(d=>docFiles(d.id).slice(0,4));if(!files.length)return;try{const {data,error}=await sb.storage.from('trip-docs').createSignedUrls(files.map(f=>f.file_path),3600);if(error)throw error;if(my!==docThumbToken)return;const urls=new Map((data||[]).map(x=>[x.path,x.signedUrl]));list.forEach(d=>{const el=$('dthumb-'+d.id),fs=docFiles(d.id);if(!el||!fs.length)return;el.innerHTML=fs.slice(0,4).map(f=>thumbHtml(f,urls.get(f.file_path))).join('')+(fs.length>4?`<span class="more">+${fs.length-4}</span>`:'')})}catch(x){console.warn('doc thumbs',x)}}
function renderDocuments(){const box=$('docList');if(!box)return;if(cache.docError){box.innerHTML=`<div class="warnbox">${esc(friendlyError(cache.docError))}</div>`;return}const tid='all',ty=$('docType')?.value||'all',q=($('docSearch')?.value||'').trim().toLowerCase();const list=cache.documents.filter(d=>(tid==='all'||d.trip_id===tid)&&(ty==='all'||d.doc_type===ty)&&(!q||[d.title,d.reference_no,d.note,docTypeName(d.doc_type)].some(v=>String(v||'').toLowerCase().includes(q))));box.innerHTML=list.length?`<div class="grid3">${list.map(docCardHtml).join('')}</div>`:`<div class="card empty">${cache.documents.length?'ไม่พบเอกสารตามเงื่อนไข':'ยังไม่มีเอกสาร'}<br><br><button class="btn w" onclick="openDocForm()">＋ เพิ่มเอกสาร</button></div>`;loadDocThumbs(list)}
function renderTripDocs(tid){const box=$('tripDocsBox');if(!box)return;if(cache.docError){box.innerHTML=`<div class="warnbox">${esc(friendlyError(cache.docError))}</div>`;return}const list=cache.documents.filter(d=>d.trip_id===tid);box.innerHTML=list.map(d=>`<div class="listitem"><div class="row"><span>${docTypeIcon(d.doc_type)}</span><div style="min-width:0;flex:1"><b>${esc(d.title)}</b><div class="muted">${esc(docTypeName(d.doc_type))}${d.reference_no?' · '+esc(d.reference_no):''} · 📎 ${docFiles(d.id).length}</div></div><span class="pill ${d.visibility==='private'?'private':''}">${d.visibility==='private'?'🔒':'👥'}</span><button class="btn sm secondary" onclick="openDocViewer('${d.id}')">เปิด</button></div></div>`).join('')||'<div class="empty">ยังไม่มีเอกสารใน Trip นี้</div>'}
async function openDocViewer(did){const d=cache.documents.find(x=>x.id===did);if(!d)return;const t=tripById(d.trip_id),s=d.schedule_id?cache.schedules.find(x=>x.id===d.schedule_id):null,files=docFiles(did),mine=d.created_by===currentUser.id&&canWrite();modal(`<div class="section"><div><h3>${docTypeIcon(d.doc_type)} ${esc(d.title)}</h3><div class="muted">${esc(docTypeName(d.doc_type))} · ${esc(t?.trip_no||'')} ${esc(t?.name||'')}</div></div><div class="spacer"></div><button class="btn secondary" onclick="closeModal()">ปิด</button></div><div class="card" style="box-shadow:none"><div class="listitem">การมองเห็น: <span class="pill ${d.visibility==='private'?'private':''}">${d.visibility==='private'?'🔒 เฉพาะฉัน':'👥 แชร์ให้สมาชิก Trip'}</span></div>${d.reference_no?`<div class="listitem">เลขที่การจอง: <b>${esc(d.reference_no)}</b></div>`:''}${d.doc_date?`<div class="listitem">วันที่: ${esc(d.doc_date)}</div>`:''}${s?`<div class="listitem">Schedule: ${esc(s.schedule_date)} · ${esc(s.activity||s.hotel_name||'')}</div>`:''}${d.note?`<div class="listitem" style="white-space:pre-wrap">${esc(d.note)}</div>`:''}</div><br><b>ไฟล์แนบ (${files.length})</b><div id="docViewThumbs" class="thumbs" style="margin-top:8px">กำลังโหลด...</div>${mine?`<br><div class="row"><button class="btn sm secondary" onclick="openDocForm('${d.id}')">แก้ไข / เพิ่มไฟล์</button><button class="btn sm danger" onclick="deleteDoc('${d.id}')">ลบเอกสาร</button></div>`:''}`);await renderThumbs('trip-docs',files,'docViewThumbs')}
function docFileListHtml(did){return docFiles(did).map(f=>`<div class="filerow"><span>${isImage(f)?'🖼️':'📄'} ${esc(f.file_name||'ไฟล์')}</span><div class="spacer"></div><button type="button" class="btn sm danger" onclick="deleteDocFile('${f.id}','${did}')">ลบ</button></div>`).join('')||'<div class="muted" style="padding:6px 0">ยังไม่มีไฟล์</div>'}
function docScheduleOptions(tid,selected){return '<option value="">-- ไม่เชื่อม --</option>'+cache.schedules.filter(s=>s.trip_id===tid).map(s=>`<option value="${s.id}" ${s.id===selected?'selected':''}>${esc(s.schedule_date)} · ${esc(s.activity||s.hotel_name||'-')}</option>`).join('')}
function refreshDocSchedules(){const el=$('dsch');if(el)el.innerHTML=docScheduleOptions($('dg').value,'')}
function onDocTypeChange(isNew){const k=docTypeKey($('dtp').value);if(!$('dtt').value.trim()&&$('dtp').value.trim())$('dtt').value=docTypeName(k);if(isNew&&k==='passport_visa'){const p=document.querySelector('input[name="dvis"][value="private"]');if(p)p.checked=true}}
async function openDocForm(did,tripId,scheduleId){try{if(cache.docError)throw new Error(DOC_SETUP_MSG);if(!curTripId)return alert('กรุณาสร้างหรือเลือก Trip ก่อน');if(!canWrite())return alert('Trip นี้แก้ไขไม่ได้');const d=did?cache.documents.find(x=>x.id===did):null;if(did&&!d)return;const tid=d?.trip_id||curTripId;const vis=d?.visibility||'shared';const isNew=d?'false':'true';
  modal(`<div class="section"><h3>${d?'แก้ไขเอกสาร':'เพิ่มเอกสาร'}</h3><div class="spacer"></div><button class="btn secondary" onclick="closeModal()">ปิด</button></div><div class="field"><label>Trip</label><select id="dg" onchange="refreshDocSchedules()" ${d?'disabled':''}>${scheduleTripOptions(tid)}</select></div><div class="field"><label>ประเภทเอกสาร</label><input id="dtp" list="dtpList" maxlength="40" value="${esc(d?docTypeName(d.doc_type):'')}" placeholder="เลือกหรือพิมพ์ประเภท" autocomplete="off" onchange="onDocTypeChange(${isNew})"><datalist id="dtpList">${Object.values(DOC_TYPES).map(v=>`<option value="${esc(v[1])}"></option>`).join('')}</datalist><div class="chips">${Object.values(DOC_TYPES).map(v=>`<button type="button" class="chip" onclick="$('dtp').value='${v[1]}';onDocTypeChange(${isNew})">${v[0]} ${v[1]}</button>`).join('')}</div></div><div class="field"><label>ชื่อเอกสาร *</label><input id="dtt" maxlength="120" value="${esc(d?.title||'')}" placeholder="เช่น ตั๋ว BKK → CNX เที่ยวไป"></div><div class="grid2"><div class="field"><label>เลขที่การจอง / PNR</label><input id="dref" value="${esc(d?.reference_no||'')}" autocapitalize="characters"></div><div class="field"><label>วันที่ใช้งาน</label><input id="ddate" type="date" value="${esc(d?.doc_date||'')}"></div></div><div class="field"><label>เชื่อมกับ Schedule (ถ้ามี)</label><select id="dsch">${docScheduleOptions(tid,d?.schedule_id||scheduleId||'')}</select></div><div class="field"><label>ใครเห็นเอกสารนี้ได้</label><div class="radiorow"><label><input type="radio" name="dvis" value="shared" ${vis==='shared'?'checked':''}> 👥 แชร์ให้สมาชิก Trip</label><label><input type="radio" name="dvis" value="private" ${vis==='private'?'checked':''}> 🔒 เฉพาะฉัน</label></div><div class="muted">แนะนำให้ตั้งพาสปอร์ต/วีซ่าเป็น "เฉพาะฉัน"</div></div><div class="field"><label>หมายเหตุ</label><textarea id="dnote">${esc(d?.note||'')}</textarea></div>${d?`<div class="field"><label>ไฟล์ที่แนบแล้ว</label><div id="docFileList" class="checklist">${docFileListHtml(d.id)}</div></div>`:''}<div class="field"><label>${d?'เพิ่มไฟล์':'แนบไฟล์'} (รูปหรือ PDF · เลือกได้หลายไฟล์)</label><input id="df" type="file" accept="image/*,.pdf" multiple><div class="muted">รูปภาพจะถูกย่อขนาดอัตโนมัติ · ไฟล์ละไม่เกิน 10 MB</div></div><button class="btn" id="saveDocBtn" onclick="saveDoc('${d?.id||''}')">บันทึก</button>`)}catch(e){err(e)}}
async function uploadDocFiles(doc,files){const uid=currentUser.id;const prepared=[];for(const f of files)prepared.push([f,await prepareUpload(f)]);for(const [orig,f] of prepared){const path=`${doc.trip_id}/${doc.id}/${uniqId()}-${safeName(f.name)}`;const {error:ue}=await sb.storage.from('trip-docs').upload(path,f,{contentType:f.type||'application/octet-stream',upsert:false});if(ue)throw ue;const {error:ie}=await sb.from('trip_document_files').insert({document_id:doc.id,file_path:path,file_name:orig.name,mime_type:f.type||null,size_bytes:f.size,created_by:uid});if(ie){await sb.storage.from('trip-docs').remove([path]);throw ie}}}
async function saveDoc(did){const btn=$('saveDocBtn');try{const existing=did?cache.documents.find(x=>x.id===did):null;const trip_id=existing?.trip_id||$('dg').value;const title=$('dtt').value.trim();if(!title)throw new Error('กรุณาระบุชื่อเอกสาร');const files=[...($('df').files||[])];files.forEach(validateFileType);if(!existing&&!files.length&&!confirm('ยังไม่ได้แนบไฟล์ ต้องการบันทึกต่อหรือไม่?'))return;const payload={schedule_id:$('dsch').value||null,doc_type:docTypeKey($('dtp').value),title,reference_no:$('dref').value.trim()||null,doc_date:$('ddate').value||null,note:$('dnote').value.trim()||null,visibility:document.querySelector('input[name="dvis"]:checked')?.value==='private'?'private':'shared'};if(btn){btn.disabled=true;btn.textContent='กำลังบันทึก...'}
  let doc;if(existing){const {data,error}=await sb.from('trip_documents').update({...payload,updated_at:new Date().toISOString()}).eq('id',did).select().single();if(error)throw error;doc=data}else{const {data,error}=await sb.from('trip_documents').insert({...payload,trip_id,created_by:currentUser.id}).select().single();if(error)throw error;doc=data}
  let warn='';if(files.length){if(btn)btn.textContent='กำลังอัปโหลดไฟล์...';try{await uploadDocFiles(doc,files)}catch(x){warn=friendlyError(x)}}
  closeModal();await render();go('documents');toast('บันทึกเอกสารแล้ว');if(warn)alert('บันทึกเอกสารแล้ว แต่อัปโหลดไฟล์ไม่สำเร็จ:\n'+warn+'\n\nเพิ่มไฟล์ภายหลังได้ที่ปุ่มแก้ไข')}catch(e){if(btn){btn.disabled=false;btn.textContent='บันทึก'}err(e)}}
async function deleteDocFile(fid,did){if(!confirm('ลบไฟล์นี้?'))return;try{const f=cache.docFiles.find(x=>x.id===fid);if(!f)return;const {error:se}=await sb.storage.from('trip-docs').remove([f.file_path]);if(se)throw se;const {error}=await sb.from('trip_document_files').delete().eq('id',fid);if(error)throw error;cache.docFiles=cache.docFiles.filter(x=>x.id!==fid);if($('docFileList'))$('docFileList').innerHTML=docFileListHtml(did);renderDocuments();toast('ลบไฟล์แล้ว')}catch(e){err(e)}}
async function deleteDoc(did){const d=cache.documents.find(x=>x.id===did);if(!d)return;if(!confirm(`ลบเอกสาร "${d.title}" และไฟล์แนบทั้งหมด?`))return;try{const paths=docFiles(did).map(f=>f.file_path);if(paths.length){const {error:se}=await sb.storage.from('trip-docs').remove(paths);if(se)throw se}const {error}=await sb.from('trip_documents').delete().eq('id',did);if(error)throw error;closeModal();await render();toast('ลบเอกสารแล้ว')}catch(e){err(e)}}
