// expenses.js — ค่าใช้จ่าย, หมวดหมู่, ใบเสร็จ, ตาราง, Settlement
const DEFAULT_CATS={hotel:'ที่พัก',food:'อาหาร',transport:'เดินทาง',activity:'กิจกรรม',shopping:'ช้อปปิ้ง',car:'รถเช่า',other:'อื่นๆ'};
function catName(v){const key={hotel:'cat_hotel',food:'cat_food',transport:'cat_transport',activity:'cat_activity',shopping:'cat_shopping',car:'cat_car',other:'cat_other'}[v];if(key)return tr(key);return v||tr('cat_other')}
function catKey(input){const s=String(input||'').trim().replace(/\s+/g,' ');if(!s)return '';if(s==='โรงแรม')return 'hotel';const keys=Object.keys(DEFAULT_CATS);const hit=keys.find(k=>k===s.toLowerCase()||DEFAULT_CATS[k]===s||catName(k)===s||I18N.th[{hotel:'cat_hotel',food:'cat_food',transport:'cat_transport',activity:'cat_activity',shopping:'cat_shopping',car:'cat_car',other:'cat_other'}[k]]===s||I18N.en[{hotel:'cat_hotel',food:'cat_food',transport:'cat_transport',activity:'cat_activity',shopping:'cat_shopping',car:'cat_car',other:'cat_other'}[k]]===s);return hit?hit:s.slice(0,40)}
function catTotals(list,gross){const o={};list.forEach(e=>{const k=e.category||'other';o[k]=(o[k]||0)+(gross?Number(e.amount||0):netOf(e))});return o}
function customCategories(){const cnt={};cache.expenses.forEach(e=>{if(e.category&&!DEFAULT_CATS[e.category])cnt[e.category]=(cnt[e.category]||0)+1});return Object.keys(cnt).sort((a,b)=>cnt[b]-cnt[a]||a.localeCompare(b,'th'))}
function categoryInput(id,value){const custom=customCategories();const keys=[...Object.keys(DEFAULT_CATS),...custom];const cur=catName(catKey(value));return `<div class="catgrid" id="${id}Grid">${keys.map(k=>{const n=catName(k),m=catMeta(k);return `<button type="button" class="catchip ${n===cur?'on':''}" data-v="${esc(n)}" style="--c:${m.color}" onclick="pickCat('${id}',this)">${catIcon(k,34)}${esc(n)}</button>`}).join('')}</div><input id="${id}" list="${id}List" value="${esc(value)}" maxlength="40" placeholder="หรือพิมพ์ชื่อหมวดใหม่" autocomplete="off" oninput="syncCatChips('${id}')" style="margin-top:8px"><datalist id="${id}List">${keys.map(k=>`<option value="${esc(catName(k))}"></option>`).join('')}</datalist>`}
function pickCat(id,btn){$(id).value=btn.dataset.v;syncCatChips(id)}
function syncCatChips(id){const v=$(id).value.trim();document.querySelectorAll(`#${id}Grid .catchip`).forEach(b=>b.classList.toggle('on',b.dataset.v===v))}
function receiptsFor(e){if(!e?.id)return [];if(cache.receiptError)return e.receipt_path?[{id:null,expense_id:e.id,file_path:e.receipt_path,file_name:e.receipt_name}]:[];return cache.receipts.filter(r=>r.expense_id===e.id)}
async function uploadReceipts(expense,files){const uid=currentUser.id;const prepared=[];for(const f of files)prepared.push([f,await prepareUpload(f)]);for(const [orig,f] of prepared){const path=`${expense.trip_id}/${uid}/${uniqId()}-${safeName(f.name)}`;const {error:ue}=await sb.storage.from('receipts').upload(path,f,{contentType:f.type||'application/octet-stream',upsert:false});if(ue)throw ue;const {error:ie}=await sb.from('expense_receipts').insert({expense_id:expense.id,file_path:path,file_name:orig.name,mime_type:f.type||null,size_bytes:f.size,created_by:uid});if(ie){await sb.storage.from('receipts').remove([path]);throw ie}}return prepared.length}
function receiptListHtml(e,editable){const rc=receiptsFor(e);return rc.map((r,i)=>`<div class="filerow"><span>${isImage(r)?'🖼️':'📄'} ${esc(r.file_name||('ใบเสร็จ '+(i+1)))}</span><div class="spacer"></div><button type="button" class="btn sm secondary" onclick="viewReceipt('${esc(r.file_path)}')">ดู</button>${editable&&r.id&&canWrite()&&(r.created_by===currentUser.id||canEditRow(e))?`<button type="button" class="btn sm danger" onclick="deleteReceipt('${r.id}','${e.id}')">ลบ</button>`:''}</div>`).join('')||'<div class="muted" style="padding:6px 0">ยังไม่มีใบเสร็จ</div>'}
async function openReceipts(eid){const e=cache.expenses.find(x=>x.id===eid);if(!e)return;const rc=receiptsFor(e);modal(`<div class="section"><div><h3>ใบเสร็จ (${rc.length})</h3><div class="muted">${esc(expName(e))} · ${money(netOf(e))}</div></div><div class="spacer"></div><button class="btn secondary" onclick="closeModal()">ปิด</button></div><div id="receiptThumbs" class="thumbs">กำลังโหลด...</div><br>${canEditRow(e)?`<button class="btn sm secondary" onclick="editExpense('${eid}')">＋ เพิ่ม / ลบใบเสร็จ</button>`:''}`);await renderThumbs('receipts',rc,'receiptThumbs')}
async function deleteReceipt(rid,eid){if(!confirm('ลบใบเสร็จนี้?'))return;try{const r=cache.receipts.find(x=>x.id===rid),e=cache.expenses.find(x=>x.id===eid);if(!r)return;const {error}=await sb.from('expense_receipts').delete().eq('id',rid);if(error)throw error;const {error:se}=await sb.storage.from('receipts').remove([r.file_path]);if(se)console.warn('remove receipt',se);if(e?.receipt_path===r.file_path)await sb.from('expenses').update({receipt_path:null,receipt_name:null}).eq('id',eid);cache.receipts=cache.receipts.filter(x=>x.id!==rid);if($('editReceipts'))$('editReceipts').innerHTML=receiptListHtml(e,true);renderExpenseTable();toast('ลบใบเสร็จแล้ว')}catch(x){err(x)}}
const EXP_COLS=[['date','วันที่'],['detail','รายการ'],['payer','ผู้จ่าย'],['category','หมวด'],['amount','จำนวนเงิน'],['receipts','ใบเสร็จ']];
let expSort=(()=>{try{const s=JSON.parse(localStorage.getItem('te_exp_sort')||'null');if(s&&EXP_COLS.some(c=>c[0]===s.key))return s}catch(_){}return {key:'date',dir:'desc'}})();
function defaultDir(k){return ['date','amount','receipts'].includes(k)?'desc':'asc'}
function setExpSort(key){if(key)expSort=expSort.key===key?{key,dir:expSort.dir==='asc'?'desc':'asc'}:{key,dir:defaultDir(key)};try{localStorage.setItem('te_exp_sort',JSON.stringify(expSort))}catch(_){}renderExpenseTable();if(typeof renderSumList==='function')renderSumList()}
function setExpSortKey(key){expSort={key,dir:defaultDir(key)};setExpSort()}
function toggleExpSortDir(){expSort={...expSort,dir:expSort.dir==='asc'?'desc':'asc'};setExpSort()}
function sortDirLabel(){const asc=expSort.dir==='asc',k=expSort.key;if(k==='date')return asc?'▲ เก่า → ใหม่':'▼ ใหม่ → เก่า';if(k==='amount'||k==='receipts')return asc?'▲ น้อย → มาก':'▼ มาก → น้อย';return asc?'▲ ก → ฮ':'▼ ฮ → ก'}
function expSortValue(e,k){switch(k){case 'date':return `${e.expense_date||''} ${String(e.expense_time||'00:00').slice(0,5)} ${e.created_at||''}`;case 'trip':return tripById(e.trip_id)?.trip_no||'';case 'detail':return e.detail||'';case 'payer':return payerName(e.payer_id);case 'category':return catName(e.category);case 'amount':return netOf(e);case 'receipts':return receiptsFor(e).length}return ''}
function filteredExpenses(){const tid='all',q=($('sumSearch')?.value||$('expSearch')?.value||'').trim().toLowerCase();return cache.expenses.filter(e=>(tid==='all'||e.trip_id===tid)&&(!q||[e.detail,catName(e.category),payerName(e.payer_id),tripById(e.trip_id)?.trip_no,tripById(e.trip_id)?.name].some(v=>String(v||'').toLowerCase().includes(q))))}
function renderExpenseTable(){const body=$('expenseTable');if(!body)return;const k=expSort.key,dir=expSort.dir==='asc'?1:-1;const list=filteredExpenses().map(e=>({e,v:expSortValue(e,k)})).sort((a,b)=>(typeof a.v==='number'?a.v-b.v:String(a.v).localeCompare(String(b.v),'th'))*dir).map(x=>x.e);
  $('expenseHead').innerHTML=EXP_COLS.map(([key,label])=>`<th class="sortable ${k===key?'sorted':''}" onclick="setExpSort('${key}')">${label} <span class="arrow">${k===key?(expSort.dir==='asc'?'▲':'▼'):'↕'}</span></th>`).join('')+'<th></th>';
  if($('expSortKey'))$('expSortKey').value=k;if($('expSortDir'))$('expSortDir').textContent=sortDirLabel();
  body.innerHTML=list.map(e=>{const t=tripById(e.trip_id);const rc=receiptsFor(e);return `<tr><td>${esc(e.expense_date)}${e.expense_time?`<div class="muted">${esc(String(e.expense_time).slice(0,5))}</div>`:''}</td><td>${esc(e.detail)}${e.schedule_id?'<div class="muted">🔗 Schedule</div>':''}</td><td>${esc(payerName(e.payer_id))}</td><td><span class="badge">${esc(catName(e.category))}</span></td><td><b>${money(netOf(e))}</b>${e.refunded?`<div class="mini okText">↩ คืนแล้ว ${money(e.refunded)}</div><div class="mini muted">เต็ม ${money(e.amount)}</div>`:''}</td><td>${rc.length?`<button class="btn sm secondary" onclick="openReceipts('${e.id}')">📎 ${rc.length}</button>`:(canEditRow(e)?`<button class="btn sm ghost" onclick="editExpense('${e.id}')">＋ เพิ่ม</button>`:'-')}</td><td>${canEditRow(e)?`<button class="btn sm secondary" onclick="editExpense('${e.id}')">แก้ไข</button> <button class="btn sm danger" onclick="deleteExpense('${e.id}')">ลบ</button>`:''}</td></tr>`}).join('')||'<tr><td colspan="7" class="empty">ไม่พบรายการ</td></tr>';
  const sum=list.reduce((a,e)=>a+netOf(e),0);$('expenseFoot').innerHTML=list.length?`<tr><td colspan="4"><b>${list.length} รายการ</b>${list.length!==cache.expenses.length?` <span class="muted">(จากทั้งหมด ${cache.expenses.length})</span>`:''}</td><td><b>${money(sum)}</b></td><td colspan="2"></td></tr>`:''}
let expFiles=[];
async function openExpenseForm(presetDate){try{if(!curTripId)return alert('กรุณาสร้างหรือเลือก Trip ก่อน');if(!canWrite())return alert('Trip นี้แก้ไขไม่ได้');expFiles=[];modal(`${addTabsHtml('expense')}<select id="eg" disabled class="hide">${scheduleTripOptions()}</select><div class="field"><label>หมวดหมู่</label>${categoryInput('ec','อาหาร')}</div><div class="field"><label>จำนวนเงิน</label><div class="amountbox"><span>฿</span><input id="ea" type="number" min="0" step="0.01" inputmode="decimal" placeholder="0.00"></div></div><div class="grid2 keep2"><div class="field"><label>วันที่</label><input id="ed" type="date" value="${esc(presetDate||today())}" oninput="renderExpSchedOptions()" onchange="renderExpSchedOptions()"></div><div class="field"><label>เวลา (ถ้ามี)</label><input id="et" type="time"></div></div><div class="field"><label>รายละเอียด</label><input id="ex" placeholder="เช่น อาหารกลางวัน (ราเมง)"></div><div class="field"><label>รูปภาพ / ใบเสร็จ</label><div class="phototiles" id="expTiles"></div><input id="er" type="file" accept="image/*,.pdf" multiple hidden onchange="addExpFiles(this)"></div><div class="field"><label>ผู้จ่าย</label><select id="ep"></select></div><details class="more"><summary>หารกับใครบ้าง (ค่าเริ่มต้น: ทุกคนเท่ากัน)<span id="shareNote" class="sharenote"></span></summary><div id="shareBox" class="checklist">กำลังโหลด...</div></details><details class="more"><summary>เชื่อมกับ Schedule</summary><select id="esched"><option value="">-- ไม่เชื่อม --</option></select></details><button class="btn big" id="createExpenseBtn" style="width:100%" onclick="createExpense()">บันทึก</button>`,'sheet full');renderExpTiles();await refreshExpenseLinks()}catch(e){err(e)}}
function renderExpTiles(){const box=$('expTiles');if(!box)return;box.innerHTML=expFiles.map((f,i)=>`<div class="ptile">${/^image\//.test(f.type)?`<img src="${URL.createObjectURL(f)}" alt="">`:'<span>📄</span>'}<button type="button" onclick="expFiles.splice(${i},1);renderExpTiles()">✕</button></div>`).join('')+`<button type="button" class="ptile add" onclick="$('er').click()"><span>＋</span><small>เพิ่มรูปภาพ</small></button>`}
function addExpFiles(input){for(const f of input.files){try{validateFileType(f);expFiles.push(f)}catch(e){alert(e.message)}}input.value='';renderExpTiles()}
async function refreshExpenseLinks(){const tid=$('eg')?.value;if(!tid)return;const [tm,ss]=await Promise.all([sb.from('trip_members').select('user_id').eq('trip_id',tid),sb.from('schedules').select('id,schedule_date,schedule_time,activity,hotel_name').eq('trip_id',tid).order('schedule_date')]);if(tm.error)throw tm.error;if(ss.error)throw ss.error;const ids=(tm.data||[]).map(x=>x.user_id);let ps=[];if(ids.length){const {data,error}=await sb.from('profiles').select('id,full_name').in('id',ids);if(error)throw error;ps=data||[]}$('ep').innerHTML=ps.map(p=>`<option value="${p.id}">${esc(p.full_name||p.id.slice(0,8))}</option>`).join('')||`<option value="${currentUser.id}">${esc(currentUser.email)}</option>`;_expScheds=ss.data||[];renderExpSchedOptions();$('shareBox').innerHTML=ps.map(p=>`<label style="display:block;padding:7px 0"><input type="checkbox" name="shareUser" value="${p.id}" checked onchange="updateShareNote()"> ${esc(p.full_name||p.id.slice(0,8))}</label>`).join('');updateShareNote();if([...$('ep').options].some(o=>o.value===currentUser.id))setSel($('ep'),currentUser.id)}
async function createExpense(){const btn=$('createExpenseBtn');try{const files=expFiles.length?[...expFiles]:[...($('er').files||[])],tripId=$('eg').value,uid=currentUser.id;const amount=Number($('ea').value||0);if(!(amount>0))throw new Error('กรุณาระบุจำนวนเงิน');const category=catKey($('ec').value);if(!category)throw new Error('กรุณาเลือกหรือพิมพ์หมวด');const chosen=[...document.querySelectorAll('input[name="shareUser"]:checked')].map(x=>x.value);if(!chosen.length)throw new Error('กรุณาเลือกสมาชิกอย่างน้อย 1 คนเพื่อคำนวณ Settlement');files.forEach(validateFileType);if(files.length&&cache.receiptError)throw new Error(RECEIPT_SETUP_MSG);if(btn){btn.disabled=true;btn.textContent='กำลังบันทึก...'}
  const {data:ex,error}=await sb.from('expenses').insert({trip_id:tripId,schedule_id:$('esched').value||null,expense_date:$('ed').value,expense_time:$('et').value||null,category,detail:$('ex').value.trim(),amount,payer_id:$('ep').value,created_by:uid}).select().single();if(error)throw error;
  const share=amount/chosen.length;const {error:se}=await sb.from('expense_participants').insert(chosen.map(user_id=>({expense_id:ex.id,user_id,share_amount:share})));if(se)throw se;
  let warn='';if(files.length){if(btn)btn.textContent='กำลังอัปโหลดใบเสร็จ...';try{await uploadReceipts(ex,files)}catch(x){warn=friendlyError(x)}}
  expFiles=[];closeModal();await render();openSummary('list');toast('บันทึกค่าใช้จ่ายแล้ว');if(warn)alert('บันทึกค่าใช้จ่ายแล้ว แต่อัปโหลดใบเสร็จไม่สำเร็จ:\n'+warn+'\n\nเพิ่มใบเสร็จภายหลังได้ที่ปุ่มแก้ไข')}catch(e){if(btn){btn.disabled=false;btn.textContent='บันทึก'}err(e)}}
async function editExpense(id){try{const e=cache.expenses.find(x=>x.id===id);if(!e)return;const {data:tm,error}=await sb.from('trip_members').select('user_id').eq('trip_id',e.trip_id);if(error)throw error;const ids=(tm||[]).map(x=>x.user_id);let ps=[];if(ids.length){const {data,error:pe}=await sb.from('profiles').select('id,full_name').in('id',ids);if(pe)throw pe;ps=data||[]}const {data:parts,error:pa}=await sb.from('expense_participants').select('user_id,share_amount').eq('expense_id',id);if(pa)throw pa;const selected=new Set((parts||[]).map(x=>x.user_id));modal(`<div class="section"><h3>แก้ไขค่าใช้จ่าย</h3><div class="spacer"></div><button class="btn secondary" onclick="closeModal()">ปิด</button></div><div class="field"><label>เชื่อมกับ Schedule</label><select id="eesched" data-trip="${esc(e.trip_id)}" data-orig="${esc(e.schedule_id||'')}">${expSchedOptionsHtml(cache.schedules.filter(s=>s.trip_id===e.trip_id),e.expense_date,e.schedule_id||'',e.schedule_id||'')}</select></div><div class="grid2"><div class="field"><label>วันที่</label><input id="eed" type="date" value="${esc(e.expense_date)}" oninput="renderExpSchedOptions('eesched','eed')" onchange="renderExpSchedOptions('eesched','eed')"></div><div class="field"><label>เวลา</label><input id="eet" type="time" value="${esc(e.expense_time||'')}"></div></div><div class="field"><label>รายการ</label><input id="eex" value="${esc(e.detail)}"></div><div class="field"><label>จำนวนเงิน</label><input id="eea" type="number" min="0" step="0.01" inputmode="decimal" value="${Number(e.amount||0)}"></div><div class="field"><label>หมวด</label>${categoryInput('eec',catName(e.category))}</div><div class="field"><label>ผู้จ่าย</label><select id="eep">${ps.map(p=>`<option value="${p.id}" ${e.payer_id===p.id?'selected':''}>${esc(p.full_name||p.id.slice(0,8))}</option>`).join('')}</select></div><div class="field"><label>หารค่าใช้จ่ายกับสมาชิก</label><div id="editShareBox" style="border:1px solid var(--line);border-radius:11px;padding:8px">${ps.map(p=>`<label style="display:block;padding:7px 0"><input type="checkbox" name="editShareUser" value="${p.id}" ${selected.has(p.id)?'checked':''}> ${esc(p.full_name||p.id.slice(0,8))}</label>`).join('')}</div></div><div class="field"><label>↩ การคืนเงิน <span class="muted">(เช่น ตั๋วเครื่องบินได้เงินคืนหลังหารกันแล้ว)</span></label><div id="editRefunds" class="checklist">${refundListHtml(e)}</div>${canRefund(e)?`<button type="button" class="btn sm secondary" style="margin-top:8px" onclick="openRefundForm('${e.id}')">＋ บันทึกการคืนเงิน</button>`:''}</div><div class="field"><label>ใบเสร็จ</label><div id="editReceipts" class="checklist">${receiptListHtml(e,true)}</div></div><div class="field"><label>เพิ่มใบเสร็จ (เลือกได้หลายไฟล์)</label><input id="eer" type="file" accept="image/*,.pdf" multiple><div class="muted">ไฟล์ใหม่จะถูกอัปโหลดเมื่อกดบันทึก</div></div><button class="btn" id="saveExpenseBtn" onclick="saveExpense('${id}')">บันทึก</button>`)}catch(e){err(e)}}
async function saveExpense(id){const btn=$('saveExpenseBtn');try{const e=cache.expenses.find(x=>x.id===id);const amount=Number($('eea').value||0);if(!(amount>0))throw new Error('กรุณาระบุจำนวนเงิน');if(amount<(e.refunded||0))throw new Error(`จำนวนเงินต้องไม่น้อยกว่ายอดที่คืนไปแล้ว (${money(e.refunded)})`);const category=catKey($('eec').value);if(!category)throw new Error('กรุณาเลือกหรือพิมพ์หมวด');const chosen=[...document.querySelectorAll('input[name="editShareUser"]:checked')].map(x=>x.value);if(!chosen.length)throw new Error('กรุณาเลือกสมาชิกอย่างน้อย 1 คน');const files=[...($('eer').files||[])];files.forEach(validateFileType);if(files.length&&cache.receiptError)throw new Error(RECEIPT_SETUP_MSG);if(btn){btn.disabled=true;btn.textContent='กำลังบันทึก...'}
  const {error}=await sb.from('expenses').update({schedule_id:$('eesched').value||null,expense_date:$('eed').value,expense_time:$('eet').value||null,detail:$('eex').value.trim(),amount,payer_id:$('eep').value,category,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error;
  const {error:de}=await sb.from('expense_participants').delete().eq('expense_id',id);if(de)throw de;const share=amount/chosen.length;const {error:ie}=await sb.from('expense_participants').insert(chosen.map(user_id=>({expense_id:id,user_id,share_amount:share})));if(ie)throw ie;
  let warn='';if(files.length){if(btn)btn.textContent='กำลังอัปโหลดใบเสร็จ...';try{await uploadReceipts(e,files)}catch(x){warn=friendlyError(x)}}
  closeModal();await render();toast('แก้ไขค่าใช้จ่ายแล้ว');if(warn)alert('บันทึกแล้ว แต่อัปโหลดใบเสร็จไม่สำเร็จ:\n'+warn)}catch(e){if(btn){btn.disabled=false;btn.textContent='บันทึก'}err(e)}}
async function viewReceipt(path){try{const {data,error}=await sb.storage.from('receipts').createSignedUrl(path,300);if(error)throw error;window.open(data.signedUrl,'_blank','noopener');}catch(e){err(e)}}
async function deleteExpense(id){if(!confirm('ลบค่าใช้จ่ายรายการนี้? ใบเสร็จที่แนบไว้จะถูกลบด้วย'))return;try{const e=cache.expenses.find(x=>x.id===id);const paths=[...new Set([...receiptsFor(e||{}).map(r=>r.file_path),e?.receipt_path].filter(Boolean))];const {error}=await sb.from('expenses').delete().eq('id',id);if(error)throw error;if(paths.length){const {error:se}=await sb.storage.from('receipts').remove(paths);if(se)console.warn('remove receipts',se)}await render();toast('ลบค่าใช้จ่ายแล้ว')}catch(e){err(e)}}
// ===================== SETTLEMENT + บันทึกการชำระ =====================
async function getSettlementData(tid){const {data:tm,error:te}=await sb.from('trip_members').select('user_id,role').eq('trip_id',tid);if(te)throw te;const ids=(tm||[]).map(x=>x.user_id);if(!ids.length)return {members:[],expenses:[],participants:[],payments:[]};const [{data:profiles,error:pe},{data:expenses,error:ee}]=await Promise.all([sb.from('profiles').select('*').in('id',ids),sb.from('expenses').select('id,trip_id,amount,payer_id,detail,expense_date').eq('trip_id',tid)]);if(pe)throw pe;if(ee)throw ee;let participants=[];const expenseIds=(expenses||[]).map(e=>e.id);if(expenseIds.length)participants=await selectIn('expense_participants','expense_id,user_id,share_amount','expense_id',expenseIds);let refunds=[];if(expenseIds.length){try{refunds=await selectIn('expense_refunds','*','expense_id',expenseIds)}catch(x){console.warn('refunds',x)}}let payments=[];const {data:pay,error:pye}=await sb.from('settlement_payments').select('*').eq('trip_id',tid);if(!pye)payments=pay||[];return {members:ids.map(id=>({id,name:displayName((profiles||[]).find(p=>p.id===id)||{id})})),expenses:expenses||[],participants,payments,refunds}}
// เศษสตางค์: ส่วนแบ่งต่อรายการถูกปัดเป็น 2 ตำแหน่งในฐานข้อมูล (เช่น 100/3) และการโอนจริงเป็นสตางค์ ทำให้เหลือเศษไม่กี่สตางค์ ถือว่าชำระครบเมื่อเหลือไม่เกิน TOL
// (ค่า 0.05 ต้องตรงกับ TOL ใน calculateSettlement)
function netShown(n){return Math.abs(n)<0.05?0:n}
function calculateSettlement(d){const TOL=0.05;const paid={},owed={},sent={},recv={};d.members.forEach(m=>{paid[m.id]=0;owed[m.id]=0;sent[m.id]=0;recv[m.id]=0});const byExp=new Map();d.participants.forEach(p=>{if(!byExp.has(p.expense_id))byExp.set(p.expense_id,[]);byExp.get(p.expense_id).push(p)});const refByExp=new Map();(d.refunds||[]).forEach(r=>{if(!refByExp.has(r.expense_id))refByExp.set(r.expense_id,[]);refByExp.get(r.expense_id).push(r)});let refundTotal=0;
  for(const e of d.expenses){const amt=Number(e.amount||0);paid[e.payer_id]=(paid[e.payer_id]||0)+amt;
    // ส่วนที่แต่ละคนต้องรับผิดชอบก่อนคืนเงิน
    const shares={};const ps=byExp.get(e.id);if(ps&&ps.length)ps.forEach(p=>{shares[p.user_id]=(shares[p.user_id]||0)+Number(p.share_amount||0)});else if(d.members.length)d.members.forEach(m=>shares[m.id]=amt/d.members.length);
    // ส่วนแบ่งที่ปัดเศษแล้วรวมกันอาจไม่เท่ายอดรายการ (คลาดไม่กี่สตางค์) → ปรับสัดส่วนให้รวมเท่ายอดจริง
    if(ps&&ps.length){const sm=Object.values(shares).reduce((x,y)=>x+y,0),df=Math.abs(sm-amt);if(sm>0&&df>1e-9&&df<=0.01*ps.length+0.005){const f=amt/sm;Object.keys(shares).forEach(k=>shares[k]*=f)}}
    // การคืนเงิน: คนที่ได้รับเงินคืนถือว่าจ่ายน้อยลง, ส่วนที่ต้องรับผิดชอบลดลงเฉพาะคนที่ระบุ หรือทุกคนตามสัดส่วน
    let prop=0;(refByExp.get(e.id)||[]).forEach(r=>{const ra=Number(r.amount||0);refundTotal+=ra;paid[r.refunded_to]=(paid[r.refunded_to]||0)-ra;if(r.for_user&&shares[r.for_user]!=null){const take=Math.min(ra,shares[r.for_user]);shares[r.for_user]-=take;prop+=ra-take}else prop+=ra});
    if(prop>0){const tot=Object.values(shares).reduce((x,y)=>x+y,0);if(tot>0){const f=Math.max(0,(tot-prop)/tot);Object.keys(shares).forEach(k=>shares[k]*=f)}}
    Object.entries(shares).forEach(([k,v])=>owed[k]=(owed[k]||0)+v)}
  (d.payments||[]).forEach(p=>{const a=Number(p.amount||0);sent[p.from_user]=(sent[p.from_user]||0)+a;recv[p.to_user]=(recv[p.to_user]||0)+a});
  const balances=d.members.map(m=>({id:m.id,name:m.name,paid:paid[m.id]||0,owed:owed[m.id]||0,sent:sent[m.id]||0,recv:recv[m.id]||0,net:(paid[m.id]||0)-(owed[m.id]||0)+(sent[m.id]||0)-(recv[m.id]||0)}));
  const creditors=balances.filter(x=>x.net>TOL).map(x=>({...x,remaining:x.net})).sort((a,b)=>b.remaining-a.remaining);const debtors=balances.filter(x=>x.net<-TOL).map(x=>({...x,remaining:-x.net})).sort((a,b)=>b.remaining-a.remaining);const transfers=[];let i=0,j=0;while(i<debtors.length&&j<creditors.length){const amt=Math.min(debtors[i].remaining,creditors[j].remaining);if(amt>0.005)transfers.push({from:debtors[i].name,to:creditors[j].name,fromId:debtors[i].id,toId:creditors[j].id,amount:Math.round(amt*100)/100});debtors[i].remaining-=amt;creditors[j].remaining-=amt;if(debtors[i].remaining<=0.005)i++;if(creditors[j].remaining<=0.005)j++}
  return {balances,transfers,total:d.expenses.reduce((a,e)=>a+Number(e.amount||0),0)-refundTotal,refundTotal,paidTotal:(d.payments||[]).reduce((a,p)=>a+Number(p.amount||0),0)}}
function canRecordPayment(x){return canWrite()&&(x.fromId===currentUser.id||x.toId===currentUser.id||isTripAdmin())}
async function renderSettlement(tid,target='settlementBox',compact=false){const box=$(target);if(!box)return;if(!tid){box.innerHTML='<div class="empty">ยังไม่มี Trip</div>';return}box.innerHTML='<div class="empty">กำลังคำนวณ Settlement...</div>';try{const d=await getSettlementData(tid);const r=calculateSettlement(d);const names=new Map(d.members.map(m=>[m.id,m.name]));
  const transferRow=x=>`<div class="listitem"><div class="row"><div><b>${esc(x.from)}</b> → <b>${esc(x.to)}</b></div><div class="spacer"></div><b>${money(x.amount)}</b></div>${pairPaid(d.payments,x.fromId,x.toId)>0.005?`<div class="mini muted" data-no-tr="1">${LANG==='en'?`Paid so far ${money(pairPaid(d.payments,x.fromId,x.toId))} · remaining ${money(x.amount)}`:`ชำระมาแล้ว ${money(pairPaid(d.payments,x.fromId,x.toId))} · คงเหลือ ${money(x.amount)}`}</div>`:''}${canRecordPayment(x)?`<div class="row" style="margin-top:6px"><div class="spacer"></div><button class="btn sm secondary" onclick="openPaymentForm('${x.fromId}','${x.toId}',${x.amount})">✔ บันทึกว่าชำระแล้ว</button></div>`:''}</div>`;
  if(compact){box.innerHTML=r.total?(r.transfers.length?`<div class="muted" style="margin-bottom:6px">ค้างชำระ ${r.transfers.length} รายการ</div>${r.transfers.slice(0,5).map(transferRow).join('')}${r.transfers.length>5?`<div class="muted">+${r.transfers.length-5} รายการ</div>`:''}`:'<div class="okbox">✔ ชำระครบแล้ว ไม่มียอดค้าง</div>'):'<div class="empty">ยังไม่มีค่าใช้จ่าย</div>';return}
  const pays=(d.payments||[]).slice().sort((a,b)=>String(b.paid_at).localeCompare(String(a.paid_at)));
  box.innerHTML=`<div class="statgrid"><div class="stat"><span class="muted">ค่าใช้จ่ายสุทธิ</span><b>${money(r.total)}</b>${r.refundTotal?`<div class="mini okText">หักเงินคืน ${money(r.refundTotal)}</div>`:''}</div><div class="stat"><span class="muted">ชำระคืนแล้ว</span><b>${money(r.paidTotal)}</b></div><div class="stat"><span class="muted">รายการที่ยังค้าง</span><b class="${r.transfers.length?'dangerText':'okText'}">${r.transfers.length}</b></div></div><br><div class="grid2"><div class="card" style="box-shadow:none"><div class="section"><h4 style="margin:0">ยอดของแต่ละคน</h4></div>${r.balances.map(x=>`<div class="listitem"><div class="row"><b>${esc(x.name)}</b><div class="spacer"></div><b class="${netShown(x.net)>=0?'okText':'dangerText'}">${netShown(x.net)>0?'+':''}${money(netShown(x.net))}</b></div><div class="mini muted">จ่าย ${money(x.paid)} · ส่วนของตัวเอง ${money(x.owed)}${x.sent||x.recv?` · โอนแล้ว ${money(x.sent)} · รับแล้ว ${money(x.recv)}`:''}</div><div class="muted">${netShown(x.net)>0?'ควรได้รับคืน':netShown(x.net)<0?'ต้องจ่ายเพิ่ม':'สมดุล'}</div></div>`).join('')||'<div class="empty">ไม่มีสมาชิก</div>'}</div><div class="card" style="box-shadow:none"><div class="section"><h4 style="margin:0">รายการที่ต้องชำระคืน</h4></div>${r.transfers.map(transferRow).join('')||(r.total?'<div class="okbox">✔ ชำระครบแล้ว</div>':'<div class="empty">ไม่มีรายการต้องโอนคืน</div>')}</div></div>${pays.length?`<br><div class="card" style="box-shadow:none"><div class="section"><h4 style="margin:0">ประวัติการชำระ (${pays.length})</h4></div>${pays.map(p=>`<div class="listitem"><div class="row"><div style="min-width:0;flex:1">✔ <b>${esc(names.get(p.from_user)||memberName(p.from_user))}</b> → <b>${esc(names.get(p.to_user)||memberName(p.to_user))}</b><div class="muted">${esc(new Date(p.paid_at).toLocaleString('th-TH'))}${p.note?' · '+esc(p.note):''}</div></div><b>${money(p.amount)}</b>${canWrite()&&(p.created_by===currentUser.id||isTripAdmin())?`<button class="btn sm danger" onclick="deletePayment('${p.id}')">ลบ</button>`:''}</div></div>`).join('')}</div>`:''}<br><div class="muted mini">หากค่าใช้จ่ายเก่าไม่มีการเลือกผู้ร่วมหาร ระบบจะแบ่งเท่ากันให้สมาชิกทุกคนของ Trip · กด "บันทึกว่าชำระแล้ว" เมื่อโอนเงินกันจริงแล้ว</div>`}catch(e){box.innerHTML='<div class="empty dangerText">คำนวณไม่ได้: '+esc(friendlyError(e))+'</div>'}}
function pairPaid(list,from,to){return Math.round((list||[]).filter(p=>p.from_user===from&&p.to_user===to).reduce((a,p)=>a+Number(p.amount||0),0)*100)/100}
function payRemaining(total,amt){return Math.round((Number(total||0)-Number(amt||0))*100)/100}
function payRemainUpdate(){const inp=$('payAmt'),out=$('payRemain');if(!inp||!out)return;const total=Number(inp.dataset.total||0),amt=Number(inp.value||0),r=payRemaining(total,amt),en=LANG==='en';
 if(!(amt>0)){out.className='muted';out.textContent=en?'Enter the amount you are paying now':'ใส่จำนวนเงินที่ชำระครั้งนี้';return}
 if(r<-0.005){out.className='dangerText';out.textContent=en?`More than the amount due by ${money(-r)}`:`เกินยอดค้างอยู่ ${money(-r)}`;return}
 if(r<=0.005){out.className='okText';out.textContent=en?'Paid in full - nothing left':'ชำระครบ ไม่มียอดคงเหลือ';return}
 out.className='';out.innerHTML=(en?'Remaining after this payment: ':'คงเหลือหลังชำระครั้งนี้: ')+'<b>'+money(r)+'</b>'+(en?' (to pay next time)':' (ชำระรอบหน้า)')}
function payFill(frac){const inp=$('payAmt');if(!inp)return;const t=Number(inp.dataset.total||0);inp.value=(Math.round(t*frac*100)/100).toFixed(2);payRemainUpdate()}
function openPaymentForm(from,to,amount){const en=LANG==='en',before=pairPaid(cache.payments,from,to);
 modal(`<div class="section"><h3>บันทึกการชำระคืน</h3><div class="spacer"></div><button class="btn secondary" onclick="closeModal()">ปิด</button></div><p><b>${esc(memberName(from))}</b> โอนให้ <b>${esc(memberName(to))}</b></p><div class="card" style="box-shadow:none;margin-bottom:10px" data-no-tr="1"><div class="row"><span class="muted">${en?'Amount due':'ยอดค้างชำระ'}</span><div class="spacer"></div><b>${money(amount)}</b></div>${before>0.005?`<div class="row mini muted"><span>${en?'Already paid earlier':'ชำระไปแล้วก่อนหน้านี้'}</span><div class="spacer"></div><span>${money(before)}</span></div>`:''}</div><div class="field"><label>จำนวนเงินที่โอน (บาท)</label><input id="payAmt" type="number" min="0.01" step="0.01" inputmode="decimal" value="${amount}" data-total="${amount}" oninput="payRemainUpdate()"><div class="row" style="margin-top:6px;gap:6px" data-no-tr="1"><button type="button" class="btn sm secondary" onclick="payFill(1)">${en?'Full amount':'เต็มจำนวน'}</button><button type="button" class="btn sm secondary" onclick="payFill(.5)">${en?'Half':'ครึ่งหนึ่ง'}</button></div><div class="muted">แก้ได้ถ้าโอนไม่เต็มจำนวน</div><div id="payRemain" class="muted" style="margin-top:6px" data-no-tr="1"></div></div><div class="field"><label>หมายเหตุ</label><input id="payNote" placeholder="เช่น โอนผ่าน PromptPay"></div><button class="btn" id="payBtn" onclick="savePayment('${from}','${to}')">บันทึก</button>`);payRemainUpdate()}
async function savePayment(from,to){const btn=$('payBtn');try{const amount=Math.round(Number($('payAmt').value||0)*100)/100;if(!(amount>0))throw new Error('กรุณาระบุจำนวนเงิน');const due=Number($('payAmt').dataset.total||0);if(due>0&&amount>due+0.005&&!confirm(LANG==='en'?`This is ${money(amount-due)} more than the amount due. Save anyway?`:`จำนวนนี้เกินยอดค้างอยู่ ${money(amount-due)} ต้องการบันทึกต่อหรือไม่?`))return;btn.disabled=true;const {error}=await sb.from('settlement_payments').insert({trip_id:curTripId,from_user:from,to_user:to,amount,note:$('payNote').value.trim()||null,created_by:currentUser.id});if(error)throw error;closeModal();await render();toast('บันทึกการชำระแล้ว')}catch(e){if(btn)btn.disabled=false;err(e)}}
async function deletePayment(id){if(!confirm('ลบรายการชำระนี้? ยอดค้างจะกลับมาเหมือนเดิม'))return;try{const {error}=await sb.from('settlement_payments').delete().eq('id',id);if(error)throw error;await render();toast('ลบแล้ว')}catch(e){err(e)}}
function renderExpenseSummary(){const p=paidNetByUser();$('expenseSummary').innerHTML=Object.entries(p).sort((a,b)=>b[1]-a[1]).map(([id,v])=>`<div class="listitem"><div class="row"><b>${esc(payerName(id))}</b><div class="spacer"></div><b>${money(v)}</b></div></div>`).join('')||'<div class="empty">ยังไม่มีข้อมูล</div>';renderSettlement(curTripId,'settlementBox')}

// ===================== REFUNDS (คืนเงิน) =====================
function annotateRefunds(){const m={};cache.refunds.forEach(r=>m[r.expense_id]=(m[r.expense_id]||0)+Number(r.amount||0));cache.expenses.forEach(e=>{e.refunded=Math.round((m[e.id]||0)*100)/100;e.net=Math.round((Number(e.amount||0)-e.refunded)*100)/100})}
function netOf(e){return e?.net??Number(e?.amount||0)}
function refundsFor(eid){return cache.refunds.filter(r=>r.expense_id===eid).sort((a,b)=>String(a.refund_date).localeCompare(String(b.refund_date)))}
function paidNetByUser(){const p={};cache.expenses.forEach(e=>p[e.payer_id]=(p[e.payer_id]||0)+Number(e.amount||0));cache.refunds.forEach(r=>p[r.refunded_to]=(p[r.refunded_to]||0)-Number(r.amount||0));return p}
function canRefund(e){return canWrite()&&!cache.refundError&&(e.created_by===currentUser.id||e.payer_id===currentUser.id||isTripAdmin())}
function refundListHtml(e){if(cache.refundError)return '<div class="warnbox">ยังไม่ได้ติดตั้งระบบคืนเงิน กรุณารัน sql/v14_1_refunds.sql</div>';const rs=refundsFor(e.id);return rs.map(r=>`<div class="filerow"><span>↩ <b>${money(r.amount)}</b> · ${esc(r.refund_date)} · คืนให้ ${esc(memberName(r.refunded_to))}${r.for_user?` · หักจากส่วนของ ${esc(memberName(r.for_user))}`:' · หักทุกคนตามสัดส่วน'}${r.note?' · '+esc(r.note):''}</span><div class="spacer"></div>${canRefund(e)?`<button type="button" class="btn sm danger" onclick="deleteRefund('${r.id}','${e.id}')">ลบ</button>`:''}</div>`).join('')+(rs.length?`<div class="mini muted" style="padding-top:6px">ยอดเต็ม ${money(e.amount)} · คืนแล้ว ${money(e.refunded)} · <b>สุทธิ ${money(netOf(e))}</b></div>`:'<div class="muted" style="padding:6px 0">ยังไม่มีการคืนเงิน</div>')}
async function openRefundForm(eid){const e=cache.expenses.find(x=>x.id===eid);if(!e)return;const remain=Math.round((Number(e.amount||0)-(e.refunded||0))*100)/100;if(remain<=0)return alert('รายการนี้คืนเงินครบเต็มจำนวนแล้ว');let parts=[];try{const {data}=await sb.from('expense_participants').select('user_id,share_amount').eq('expense_id',eid);parts=data||[]}catch(_){}const people=parts.length?parts.map(p=>p.user_id):cache.tripMembers.map(m=>m.user_id);const opt=(id,sel)=>`<option value="${id}" ${id===sel?'selected':''}>${esc(memberName(id))}</option>`;
  modal(`<div class="section"><div><h3>↩ บันทึกการคืนเงิน</h3><div class="muted">${esc(e.detail||catName(e.category))} · ยอดเต็ม ${money(e.amount)}${e.refunded?` · คืนแล้ว ${money(e.refunded)}`:''}</div></div><div class="spacer"></div><button class="btn secondary" onclick="editExpense('${eid}')">กลับ</button></div><div class="field"><label>จำนวนเงินที่ได้คืน (ไม่เกิน ${money(remain)})</label><input id="rfAmt" type="number" min="0.01" max="${remain}" step="0.01" inputmode="decimal" value="${remain}"></div><div class="field"><label>วันที่ได้เงินคืน</label><input id="rfDate" type="date" value="${today()}"></div><div class="field"><label>ใครเป็นคนได้รับเงินคืน</label><select id="rfTo">${cache.tripMembers.map(m=>opt(m.user_id,e.payer_id)).join('')}</select><div class="muted">ปกติคือผู้จ่ายเดิม (${esc(memberName(e.payer_id))}) เพราะเงินคืนเข้าบัตร/บัญชีคนจ่าย</div></div><div class="field"><label>เงินคืนนี้เป็นส่วนของใคร</label><select id="rfFor"><option value="">ทุกคนที่ร่วมหาร (ลดตามสัดส่วน)</option>${people.map(id=>`<option value="${id}">เฉพาะส่วนของ ${esc(memberName(id))}</option>`).join('')}</select><div class="muted">ตัวอย่าง: ยกเลิกตั๋วของคนเดียว → เลือก "เฉพาะส่วนของ" คนนั้น · สายการบินคืนเงินทั้งเที่ยว → เลือก "ทุกคน"</div></div><div class="field"><label>หมายเหตุ</label><input id="rfNote" placeholder="เช่น สายการบินคืนเงินค่าธรรมเนียม"></div><button class="btn" id="rfBtn" onclick="saveRefund('${eid}')">บันทึกการคืนเงิน</button>`)}
async function saveRefund(eid){const btn=$('rfBtn');try{const e=cache.expenses.find(x=>x.id===eid);const remain=Math.round((Number(e.amount||0)-(e.refunded||0))*100)/100;const amount=Math.round(Number($('rfAmt').value||0)*100)/100;if(!(amount>0))throw new Error('กรุณาระบุจำนวนเงิน');if(amount>remain)throw new Error(`ยอดคืนเกินจำนวนที่เหลือ (${money(remain)})`);if(!$('rfDate').value)throw new Error('กรุณาเลือกวันที่');btn.disabled=true;const {error}=await sb.from('expense_refunds').insert({expense_id:eid,amount,refund_date:$('rfDate').value,refunded_to:$('rfTo').value,for_user:$('rfFor').value||null,note:$('rfNote').value.trim()||null,created_by:currentUser.id});if(error)throw error;await render();toast('บันทึกการคืนเงินแล้ว');editExpense(eid)}catch(x){if(btn)btn.disabled=false;err(x)}}
async function deleteRefund(rid,eid){if(!confirm('ลบรายการคืนเงินนี้? ยอดค่าใช้จ่ายสุทธิจะกลับไปเท่าเดิม'))return;try{const {error}=await sb.from('expense_refunds').delete().eq('id',rid);if(error)throw error;await render();toast('ลบแล้ว');editExpense(eid)}catch(x){err(x)}}

// ---------- "เชื่อมกับ Schedule": แสดงเฉพาะรายการที่วันที่ตรงกับวันที่ของค่าใช้จ่าย (เวลาไม่จำเป็น) ----------
let _expScheds=[];
function _expSchedLabel(s,other){const t=s.schedule_time?String(s.schedule_time).slice(0,5):'--:--',n=s.activity||s.hotel_name||'-';return other?`${s.schedule_date} · ${n} (คนละวัน)`:`${t} · ${n}`}
// คืน <option> ทั้งหมด: รายการของวันนั้น (เรียงตามเวลา) + รายการที่เชื่อมอยู่เดิมถ้าอยู่คนละวัน (กันลิงก์หายเงียบๆ ตอนแก้วันที่)
function expSchedOptionsHtml(list,date,selected,orig){
  const rows=(list||[]).filter(s=>s.schedule_date===date).sort((a,b)=>String(a.schedule_time||'99').localeCompare(String(b.schedule_time||'99')));
  const extra=orig&&!rows.some(s=>s.id===orig)?(list||[]).find(s=>s.id===orig):null;
  return `<option value="">${rows.length?'-- ไม่เชื่อม --':'-- ไม่มี Schedule ในวันนี้ --'}</option>`+rows.map(s=>`<option value="${s.id}"${s.id===selected?' selected':''}>${esc(_expSchedLabel(s,false))}</option>`).join('')+(extra?`<option value="${extra.id}"${extra.id===selected?' selected':''}>${esc(_expSchedLabel(extra,true))}</option>`:'')}
function renderExpSchedOptions(selId,dateId){
  selId=selId||'esched';dateId=dateId||'ed';const sel=$(selId);if(!sel)return;
  const list=sel.dataset.trip?cache.schedules.filter(s=>s.trip_id===sel.dataset.trip):_expScheds,cur=sel.value,orig=sel.dataset.orig||'';
  const keep=list.some(s=>s.id===cur&&(s.schedule_date===$(dateId)?.value||s.id===orig))?cur:'';        // วันที่เปลี่ยนจนรายการที่เลือกไม่ตรงวัน → ล้างการเลือก
  sel.innerHTML=expSchedOptionsHtml(list,$(dateId)?.value,keep,orig);setSel(sel,keep)}
// บรรทัดสรุปการหาร: ทุกคนเท่ากัน หรือเลือกเอง
function updateShareNote(){
  const all=[...document.querySelectorAll('input[name="shareUser"]')],on=all.filter(x=>x.checked).length,el=$('shareNote');if(!el)return;
  el.textContent=!all.length?'':on===all.length?`ทุกคนเท่ากัน (${all.length} คน)`:on?`เลือกเอง ${on} จาก ${all.length} คน`:'กรุณาเลือกอย่างน้อย 1 คน';
  if(typeof translateDOM==='function'&&LANG==='en')translateDOM(el)}
