// =====================================================================
// friends.js — เพื่อน: Friend Code / QR, คำขอ, รายชื่อ, บล็อก, ชวนเข้า Group/Trip
// =====================================================================
let friendsData={friends:[],incoming:[],outgoing:[],blocked:[]},myFriendCode=null,friendIds=new Set();
function friendLink(code){return APP_URL+'?friend='+encodeURIComponent(code)}
async function loadFriendsLite(){try{const {data,error}=await sb.rpc('my_friends');if(error)throw error;friendsData=data||friendsData;friendIds=new Set((friendsData.friends||[]).map(f=>f.id))}catch(x){console.warn('friends',x)}}
async function renderFriends(){const box=$('friendsBox');if(!box)return;box.innerHTML='<div class="empty">กำลังโหลด...</div>';try{const [{data:code,error:ce}]=await Promise.all([sb.rpc('get_my_friend_code'),loadFriendsLite()]);if(ce)throw ce;myFriendCode=code;const fr=friendsData.friends||[],inc=friendsData.incoming||[],out=friendsData.outgoing||[],bl=friendsData.blocked||[];let contacts=[];if(fr.length){try{const {data}=await sb.rpc('get_member_contacts',{p_user_ids:fr.map(f=>f.id)});contacts=data||[]}catch(_){}}const url=friendLink(code);const myName=displayName(me||{id:currentUser.id});const t=curTrip();const tripMemberIds=new Set(cache.tripMembers.map(m=>m.user_id));
  box.innerHTML=`<div class="grid2"><div class="card"><h3>🤝 Friend Code ของฉัน</h3><div class="grid2"><div><div class="bigcode">${esc(code)}</div><div class="row" style="gap:6px;margin:8px 0"><button class="btn sm secondary" onclick="copyText('${esc(code)}','คัดลอก Friend Code แล้ว')">📋 คัดลอก</button></div>${shareButtons('เพิ่มเพื่อนกับ '+myName,url,code)}</div><div class="qrbox">${qrSvg(url)}<div class="mini muted">ให้เพื่อนสแกนเพื่อเพิ่มเพื่อน</div></div></div></div><div class="card"><h3>➕ เพิ่มเพื่อน</h3><div class="muted mini">ใส่ Friend Code ของเพื่อน หรืออีเมลที่เพื่อนใช้สมัคร (ต้องตรงทั้งหมด)</div><div class="inrow" style="margin-top:8px"><input id="addFriendInput" placeholder="Friend Code หรือ อีเมล" autocapitalize="off" style="padding:10px;border:1px solid var(--line);border-radius:10px" onkeydown="if(event.key==='Enter')sendFriendFromInput()"><button class="btn" id="addFriendBtn" onclick="sendFriendFromInput()">ส่งคำขอ</button></div>${inc.length?`<h4 style="margin:16px 0 6px">📥 คำขอเป็นเพื่อน (${inc.length})</h4>${inc.map(x=>`<div class="listitem row"><b style="flex:1">${esc(x.name)}</b><button class="btn sm" onclick="respondFriend('${x.id}',true)">✔ ยอมรับ</button><button class="btn sm secondary" onclick="respondFriend('${x.id}',false)">ปฏิเสธ</button></div>`).join('')}`:''}${out.length?`<h4 style="margin:16px 0 6px">📤 รอเพื่อนตอบรับ (${out.length})</h4>${out.map(x=>`<div class="listitem row"><span style="flex:1">${esc(x.name)}</span><button class="btn sm secondary" onclick="removeFriend('${x.id}',true)">ยกเลิก</button></div>`).join('')}`:''}</div></div><br><div class="card"><div class="section"><h3>👥 เพื่อนของฉัน (${fr.length})</h3></div>${fr.map(f=>{const c=contacts.find(x=>x.user_id===f.id);return `<div class="listitem"><div class="row"><div style="min-width:0;flex:1"><b>${esc(f.name)}</b>${contactLinks(c)}</div>${t&&canWrite()&&!tripMemberIds.has(f.id)?`<button class="btn sm" onclick="inviteFriendTo('trip','${t.id}','${f.id}')">📨 ชวนเข้า ${esc(t.trip_no)}</button>`:''}<button class="btn sm secondary" onclick="removeFriend('${f.id}')">ลบเพื่อน</button><button class="btn sm danger" onclick="blockUser('${f.id}')">บล็อก</button></div></div>`}).join('')||'<div class="empty">ยังไม่มีเพื่อน แชร์ Friend Code ให้เพื่อนได้เลย</div>'}</div>${bl.length?`<br><div class="card"><h3>🚫 ที่บล็อกไว้</h3>${bl.map(b=>`<div class="listitem row"><span style="flex:1">${esc(b.name)}</span><button class="btn sm secondary" onclick="unblockUser('${b.id}')">เลิกบล็อก</button></div>`).join('')}</div>`:''}`}catch(e){box.innerHTML=`<div class="warnbox">${esc(friendlyError(e))}</div>`}}
async function sendFriendFromInput(){const el=$('addFriendInput'),btn=$('addFriendBtn');const v=el.value.trim();if(!v)return;btn.disabled=true;try{const args=v.includes('@')?{p_email:v}:{p_code:v};await sendFriend(args);el.value=''}catch(e){err(e)}finally{btn.disabled=false}}
async function sendFriend(args){const {data,error}=await sb.rpc('send_friend_request',args);if(error)throw error;const n=data?.name?`"${data.name}"`:'';const msg={sent:`ส่งคำขอเป็นเพื่อนถึง ${n} แล้ว`,accepted:`เป็นเพื่อนกับ ${n} แล้ว 🎉`,already_friends:`${n} เป็นเพื่อนของคุณอยู่แล้ว`,already_sent:`ส่งคำขอถึง ${n} ไปแล้ว รอตอบรับ`,self:'นี่คือ Friend Code ของคุณเอง',not_found:'ไม่พบผู้ใช้นี้ ตรวจสอบ Friend Code หรืออีเมลอีกครั้ง',too_many:'ลองหลายครั้งเกินไป กรุณารอ 15 นาที'}[data?.status]||'ดำเนินการแล้ว';if(['not_found','too_many','self'].includes(data?.status))alert(msg);else toast(msg);await loadFriendsLite();loadInbox();if($('friends')?.classList.contains('active'))renderFriends();return data}
async function addFriendById(uid){try{await sendFriend({p_user:uid});if($('modal').innerHTML&&curTripId)openTripDetail(curTripId,'members')}catch(e){err(e)}}
async function respondFriend(uid,accept){try{const {error}=await sb.rpc('respond_friend_request',{p_other:uid,p_accept:accept});if(error)throw error;toast(accept?'เป็นเพื่อนกันแล้ว 🎉':'ปฏิเสธแล้ว');await loadFriendsLite();loadInbox();if($('friends')?.classList.contains('active'))renderFriends();if($('modal').innerHTML.includes('การแจ้งเตือน'))openInbox()}catch(e){err(e)}}
async function removeFriend(uid,isCancel){if(!confirm(isCancel?'ยกเลิกคำขอเป็นเพื่อน?':'ลบเพื่อนคนนี้?'))return;try{const {error}=await sb.rpc('remove_friend',{p_other:uid});if(error)throw error;await loadFriendsLite();renderFriends()}catch(e){err(e)}}
async function blockUser(uid){if(!confirm('บล็อกผู้ใช้นี้? จะลบออกจากเพื่อน และเขาจะส่งคำขอเป็นเพื่อนถึงคุณไม่ได้'))return;try{const {error}=await sb.rpc('block_user',{p_other:uid});if(error)throw error;await loadFriendsLite();renderFriends()}catch(e){err(e)}}
async function unblockUser(uid){try{const {error}=await sb.rpc('unblock_user',{p_other:uid});if(error)throw error;renderFriends()}catch(e){err(e)}}
async function inviteFriendTo(type,id,uid){try{const {data,error}=await sb.rpc('invite_user',{p_type:type,p_id:id,p_user:uid});if(error)throw error;toast({already_member:'เพื่อนคนนี้เป็นสมาชิกอยู่แล้ว',duplicate:'มีคำเชิญค้างอยู่แล้ว',pending_admin:'ส่งคำเชิญแล้ว รอ Admin อนุมัติ',pending_invitee:'ส่งคำเชิญแล้ว รอเพื่อนตอบรับใน 🔔'}[data]||'ส่งคำเชิญแล้ว');const el=document.querySelector(`[data-invf="${uid}"]`);if(el){el.disabled=true;el.textContent='✔ เชิญแล้ว'}}catch(e){err(e)}}
async function renderFriendInviteList(type,id){const box=$('invFriends');if(!box)return;await loadFriendsLite();let members=[];if(type==='trip')members=id===curTripId?cache.tripMembers.map(m=>m.user_id):[];else{try{members=(await groupMemberProfiles(id)).map(p=>p.id)}catch(_){}}const list=(friendsData.friends||[]).filter(f=>!members.includes(f.id));box.innerHTML=list.length?list.map(f=>`<div class="filerow"><span>🤝 ${esc(f.name)}</span><div class="spacer"></div><button class="btn sm" data-invf="${f.id}" onclick="inviteFriendTo('${type}','${id}','${f.id}')">เชิญ</button></div>`).join(''):`<div class="muted mini">${(friendsData.friends||[]).length?'เพื่อนทุกคนเป็นสมาชิกแล้ว':'ยังไม่มีเพื่อน — เพิ่มเพื่อนได้ที่เมนู 🤝 Friends'}</div>`}
