// groups.js — Group, สมาชิก Group, บทบาท
async function createGroup(){const name=prompt('ชื่อ Group');if(!name)return;try{const {data,error}=await sb.rpc('create_group',{p_name:name.trim()});if(error)throw error;await render();toast('สร้าง Group สำเร็จ · Code: '+data.code);go('groups')}catch(e){err(e)}}
async function joinGroup(){const code=$('joinCode').value.trim();if(!code)return;try{const {error}=await sb.rpc('join_group_by_code',{p_code:code});if(error)throw error;$('joinCode').value='';await render();toast('เข้าร่วม Group สำเร็จ')}catch(e){err(e)}}
async function groupMemberProfiles(gid){const {data:gm,error}=await sb.from('group_members').select('user_id,role').eq('group_id',gid);if(error)throw error;const ids=(gm||[]).map(x=>x.user_id);let ps=[];if(ids.length){const {data,error:pe}=await sb.from('profiles').select('id,full_name').in('id',ids);if(pe)throw pe;ps=data||[]}return (gm||[]).map(m=>({id:m.user_id,role:m.role,name:ps.find(p=>p.id===m.user_id)?.full_name||m.user_id.slice(0,8)}))}
function renderGroups(){$('groupsList').innerHTML=cache.groups.map(g=>{const trips=cache.trips.filter(t=>t.group_id===g.id);return `<div class="card" style="margin-bottom:12px"><div class="row"><div><b>${esc(g.name)}</b><div class="muted">Code: <b>${esc(g.code)}</b> · ${roleName(g.role)} · ${trips.length} Trip</div></div><div class="spacer"></div><button class="btn sm secondary" onclick="openGroupMembers('${g.id}')">👥 สมาชิก</button></div></div>`}).join('')||'<div class="card empty">ยังไม่มี Group<br><span class="mini">สร้าง Group ใหม่ หรือใส่ Group Code ที่ได้รับจากเพื่อน</span></div>'}
async function openGroupMembers(gid){try{const g=cache.groups.find(x=>x.id===gid);if(!g)return;const people=await groupMemberProfiles(gid);const myR=g.role,isOwner=myR==='owner',isAdm=['owner','admin'].includes(myR);
  modal(`<div class="section"><div><h3>${esc(g.name)} · สมาชิก (${people.length})</h3><div class="muted">Group Code: <b>${esc(g.code)}</b> · บทบาทของคุณ: ${roleName(myR)}</div></div><div class="spacer"></div><button class="btn secondary" onclick="closeModal()">ปิด</button></div>${people.map(p=>{const self=p.id===currentUser.id;const canRemove=!self&&p.role!=='owner'&&(isOwner||(isAdm&&p.role==='member'));return `<div class="listitem"><div class="row"><div style="min-width:0;flex:1"><b>${esc(p.name)}</b>${self?' <span class="muted">(คุณ)</span>':''}<div class="muted">${roleName(p.role)}</div></div>${isOwner&&!self&&p.role!=='owner'?`<select onchange="setGroupRole('${gid}','${p.id}',this.value)" style="padding:6px;border-radius:8px;border:1px solid var(--line)"><option value="member" ${p.role==='member'?'selected':''}>Member</option><option value="admin" ${p.role==='admin'?'selected':''}>Admin</option></select>`:''}${canRemove?`<button class="btn sm danger" onclick="removeGroupMember('${gid}','${p.id}')">นำออก</button>`:''}</div></div>`}).join('')||'<div class="empty">ไม่มีสมาชิก</div>'}${myR!=='owner'?`<br><button class="btn sm danger" onclick="leaveGroup('${gid}')">ออกจาก Group</button>`:''}<div class="mini muted" style="margin-top:10px">การนำออกจาก Group ไม่ได้นำออกจาก Trip ที่เข้าร่วมอยู่แล้ว</div>`)}catch(e){err(e)}}
async function setGroupRole(gid,uid,role){try{const {error}=await sb.rpc('set_group_member_role',{p_group_id:gid,p_user_id:uid,p_role:role});if(error)throw error;toast('เปลี่ยนบทบาทแล้ว');await render();openGroupMembers(gid)}catch(e){err(e);openGroupMembers(gid)}}
async function removeGroupMember(gid,uid){if(!confirm('นำสมาชิกคนนี้ออกจาก Group?'))return;try{const {error}=await sb.rpc('remove_group_member',{p_group_id:gid,p_user_id:uid});if(error)throw error;toast('นำออกแล้ว');await render();openGroupMembers(gid)}catch(e){err(e)}}
async function leaveGroup(gid){if(!confirm('ออกจาก Group นี้? คุณจะยังอยู่ใน Trip ที่เข้าร่วมไว้แล้ว'))return;try{const {error}=await sb.rpc('leave_group',{p_group_id:gid});if(error)throw error;closeModal();await render();toast('ออกจาก Group แล้ว')}catch(e){err(e)}}
