// =====================================================================
// history.js — ประวัติการเดินทาง: สรุปทุก Trip ที่ปิดแล้วของฉัน จัดกลุ่มตามปี
// =====================================================================
let historyData=null;
function historyYear(t){return t.start_date?new Date(t.start_date+'T00:00:00').getFullYear():(t.closed_at?new Date(t.closed_at).getFullYear():null)}
function thaiYear(y){return y?(y+543):'ไม่ระบุปี'}
async function renderHistory(){const box=$('historyBox');if(!box)return;box.innerHTML='<div class="empty">กำลังโหลด...</div>';try{const {data,error}=await sb.rpc('my_travel_history');if(error)throw error;historyData=data||[];drawHistory()}catch(e){box.innerHTML=`<div class="warnbox">${esc(friendlyError(e))}</div>`}}
function drawHistory(){const box=$('historyBox');const list=historyData||[];if(!list.length){box.innerHTML=`<div class="card empty"><div class="bigicon">${lineIcon('history')}</div><h3 style="margin:6px 0">ยังไม่มีทริปที่จบแล้ว</h3><div class="muted">เมื่อปิด Trip ที่เดินทางเสร็จแล้ว จะเก็บไว้ในหน้านี้เป็นความทรงจำ</div></div>`;return}
  const totalAll=list.reduce((a,t)=>a+Number(t.total||0),0),daysAll=list.reduce((a,t)=>a+Number(t.days||0),0);
  const groups={};list.forEach(t=>{const y=historyYear(t);(groups[y]=groups[y]||[]).push(t)});
  const years=Object.keys(groups).sort((a,b)=>(b==='null'?-1:b)-(a==='null'?-1:a));
  box.innerHTML=`<div class="card histsum"><div><div class="muted mini">ทริปที่จบแล้ว</div><b>${list.length}</b></div><div><div class="muted mini">ใช้จ่ายรวมทั้งหมด</div><b>${money(totalAll)}</b></div><div><div class="muted mini">รวมวันเดินทาง</div><b>${daysAll} วัน</b></div></div>`+years.map(y=>`<div class="histyear">${y==='null'?'ไม่ระบุปี':(LANG==='en'?'Year '+y:'ปี '+thaiYear(Number(y)))}</div><div class="histgrid">${groups[y].map(histCardHtml).join('')}</div>`).join('');hydrateMedia(box)}
function histCardHtml(t){const places=(t.places||[]).slice(0,3);return `<div class="histcard" onclick="openHistoryDetail('${t.id}')"><div class="histcover"${t.photo_path?` data-av="${esc(t.photo_path)}"`:''}><span class="histyearbadge">${esc(fmtDate(t.start_date,{day:'numeric',month:'short'}))}${t.end_date&&t.end_date!==t.start_date?' – '+esc(fmtDate(t.end_date,{day:'numeric',month:'short',year:'numeric'})):''}</span></div><div class="histbody"><b>${esc(t.name)}</b><div class="mini muted">📍 ${esc(t.destination||places[0]||'ไม่ระบุสถานที่')}${t.days?' · '+t.days+(LANG==="en"?' days':' วัน'):''}</div><div class="row" style="margin-top:6px"><b>${money(t.total)}</b><div class="spacer"></div><span class="mini muted">👥 ${t.members}</span></div></div></div>`}
function openHistoryDetail(id){const t=(historyData||[]).find(x=>x.id===id);if(!t)return;const places=t.places||[];modal(`<div class="sheethead"><h3>${esc(t.name)}</h3><div class="spacer"></div><button class="btn secondary sm" onclick="closeModal()">ปิด</button></div><div class="covereditor"${t.photo_path?` data-av="${esc(t.photo_path)}"`:''}></div><div class="listitem">📅 ${esc(fmtRange(t))}${t.days?` (${t.days} วัน)`:''}</div><div class="listitem">📍 ${esc(t.destination||'ไม่ระบุสถานที่')}</div>${places.length?`<div class="listitem">🏨 สถานที่พัก/เที่ยว: ${places.map(esc).join(', ')}</div>`:''}<div class="listitem">💰 ใช้จ่ายรวม <b>${money(t.total)}</b> (${t.expense_count} รายการ)${t.top_category?' · ส่วนใหญ่เป็น '+esc(catName(t.top_category)):''}</div><div class="listitem">👥 สมาชิก ${t.members} คน</div><br><button class="btn w" style="width:100%" onclick="closeModal();switchTrip('${t.id}')">เปิดดู Dashboard ของทริปนี้</button>`,'sheet');hydrateMedia($('modal'))}
