// =====================================================================
// invites.js — Code, QR, ลิงก์เชิญ, เชิญทางอีเมล, การตั้งค่าเข้าร่วม, คำขอ/อนุมัติ, กล่องแจ้งเตือน 🔔
// =====================================================================
function POLICY_(){return {open:['🟢',tr('pol_open'),LANG==='en'?'Use the code to join instantly':'ใช้ Code แล้วเข้าร่วมได้ทันที'],password:['🔑',tr('pol_password'),LANG==='en'?'Requires the code and a password':'ต้องใช้ Code และรหัสผ่าน'],invite_only:['✉️',tr('pol_invite'),LANG==='en'?'Code cannot be used — invite or invite link required':'ใช้ Code ไม่ได้ ต้องได้รับคำเชิญหรือลิงก์เชิญ']}}
Object.defineProperty(window,'POLICY',{get:POLICY_});
function policyBadge(p){const x=POLICY[p]||POLICY.open;return `<span class="pill pol-${esc(p||'open')}" title="${esc(x[2])}">${x[0]} ${x[1]}</span>`}
let inbox={invites:[],approvals:[],my_requests:[]};

// ---------- ลิงก์ / QR / แชร์ ----------
function joinLink(code){return APP_URL+'?join='+encodeURIComponent(code)}
function inviteTokenLink(token){return APP_URL+'?invite='+encodeURIComponent(token)}
function qrSvg(text){try{const q=qrcode(0,'M');q.addData(text);q.make();return q.createSvgTag({cellSize:4,margin:2,scalable:true})}catch(e){console.warn('qr',e);return '<div class="muted mini">สร้าง QR ไม่ได้ (ตรวจสอบอินเทอร์เน็ต)</div>'}}
async function copyText(t,msg){try{await navigator.clipboard.writeText(t);toast(msg||'คัดลอกแล้ว')}catch(_){prompt('คัดลอกข้อความนี้',t)}}
function inviteMessage(name,url,code){return `ชวนเข้าร่วม "${name}" ใน FriendTrip Go\n${url}${code?`\nหรือใส่ Code: ${code}`:''}`}
async function shareInvite(name,url,code){const text=inviteMessage(name,url,code);if(navigator.share){try{await navigator.share({title:'FriendTrip Go',text});return}catch(e){if(e&&e.name==='AbortError')return}}copyText(text,'คัดลอกข้อความเชิญแล้ว นำไปวางในแชตได้เลย')}
function shareLine(name,url,code){window.open('https://line.me/R/share?text='+encodeURIComponent(inviteMessage(name,url,code)),'_blank','noopener')}
function shareButtons(name,url,code){const n=esc(name).replace(/'/g,'&#39;');return `<div class="row" style="gap:6px"><button class="btn sm secondary" onclick="copyText('${esc(url)}','คัดลอกลิงก์แล้ว')">🔗 คัดลอกลิงก์</button><button class="btn sm secondary" onclick="shareInvite(this.dataset.n,'${esc(url)}','${esc(code||'')}')" data-n="${esc(name)}">📤 แชร์</button><button class="btn sm line" onclick="shareLine(this.dataset.n,'${esc(url)}','${esc(code||'')}')" data-n="${esc(name)}">💬 LINE</button></div>`}

// ---------- ข้อมูลเป้าหมาย ----------
function inviteTarget(type,id){if(type==='group'){const g=cache.groups.find(x=>x.id===id);return g?{type,id,name:g.name,code:g.code,policy:g.join_policy||'open',isAdmin:['owner','admin'].includes(g.role),isMember:true}:null}const t=tripById(id);return t?{type,id,name:`${t.trip_no} · ${t.name}`,code:t.code,policy:t.join_policy||'open',isAdmin:canAdmin(id),isMember:!!myRole(id),closed:isClosed(t)}:null}

// ---------- หน้าต่าง "เชิญสมาชิก" ----------
async function openInviteModal(type,id){try{const x=inviteTarget(type,id);if(!x)return;if(!x.isMember)return alert('เฉพาะสมาชิกเท่านั้นที่เชิญได้');if(!x.code)return alert('ยังไม่มี Code กรุณารันไฟล์ sql/v15_join.sql ก่อน');const url=joinLink(x.code);const codeUsable=x.policy!=='invite_only';
  modal(`<div class="section"><div><h3>📨 เชิญเข้า${type==='group'?' Group':' Trip'}</h3><div class="muted">${esc(x.name)}</div></div><div class="spacer"></div><button class="btn secondary" onclick="closeModal()">ปิด</button></div><div class="row" style="gap:6px;margin-bottom:12px">${policyBadge(x.policy)}<span class="muted mini">${esc(POLICY[x.policy]?.[2]||'')}</span></div>${x.closed?'<div class="warnbox">Trip นี้ปิดแล้ว เชิญคนใหม่ไม่ได้จนกว่าจะเปิด Trip อีกครั้ง</div>':''}
  <div class="card invitecard" style="box-shadow:none"><div class="grid2"><div><div class="muted">Code</div><div class="bigcode">${esc(x.code)}</div><div class="row" style="gap:6px;margin:8px 0"><button class="btn sm secondary" onclick="copyText('${esc(x.code)}','คัดลอก Code แล้ว')">📋 คัดลอก Code</button></div>${codeUsable?shareButtons(x.name,url,x.code):'<div class="warnbox">ตั้งเป็น "เชิญเท่านั้น" — Code และ QR นี้ใช้เข้าร่วมไม่ได้ ใช้ "ลิงก์เชิญพิเศษ" หรือเชิญทางอีเมลแทน</div>'}${x.policy==='password'?'<div class="mini muted" style="margin-top:8px">🔑 ผู้เข้าร่วมต้องใส่รหัสผ่าน อย่าลืมบอกรหัสผ่านแยกให้เฉพาะคนที่ต้องการเชิญ</div>':''}</div><div class="qrbox ${codeUsable?'':'dim'}">${qrSvg(url)}<div class="mini muted">สแกนด้วยกล้องมือถือ</div></div></div></div>
  <br><div class="card" style="box-shadow:none"><b>✉️ เชิญทางอีเมล</b><div class="muted mini">ผู้ถูกเชิญจะเห็นคำเชิญใน 🔔 เมื่อเข้าสู่ระบบด้วยอีเมลนี้ (ระบบไม่ได้ส่งอีเมลออกไป แนะนำให้ส่งลิงก์ให้ด้วย)${x.isAdmin?'':' · คำเชิญของคุณจะรอ Admin อนุมัติก่อน'}</div><div class="inrow" style="margin-top:8px"><input id="invEmail" type="email" placeholder="friend@email.com" style="padding:10px;border:1px solid var(--line);border-radius:10px"><button class="btn" id="invEmailBtn" onclick="inviteEmail('${type}','${id}')">ส่งคำเชิญ</button></div><div id="invPending" style="margin-top:10px"></div></div><br><div class="card" style="box-shadow:none"><b>🤝 เชิญจากรายชื่อเพื่อน</b>${x.isAdmin?'':'<div class="muted mini">คำเชิญจะรอ Admin อนุมัติก่อน</div>'}<div id="invFriends" style="margin-top:8px"><div class="muted mini">กำลังโหลด...</div></div></div>
  ${x.isAdmin?`<br><div class="card" style="box-shadow:none"><b>⚙️ ตั้งค่าการเข้าร่วม (Admin)</b><div class="field"><div class="radiorow">${Object.entries(POLICY).map(([k,v])=>`<label><input type="radio" name="polSel" value="${k}" ${k===x.policy?'checked':''} onchange="$('polPwBox').classList.toggle('hide',this.value!=='password')"> ${v[0]} ${v[1]}</label>`).join('')}</div></div><div id="polPwBox" class="field ${x.policy==='password'?'':'hide'}"><label>รหัสผ่านสำหรับเข้าร่วม ${x.policy==='password'?'<span class="muted">(เว้นว่าง = ใช้รหัสเดิม)</span>':''}</label><input id="polPw" type="text" autocomplete="off" placeholder="อย่างน้อย 4 ตัวอักษร"></div><div class="row"><button class="btn sm" id="polBtn" onclick="saveJoinPolicy('${type}','${id}')">บันทึกการตั้งค่า</button><button class="btn sm secondary" onclick="regenCode('${type}','${id}')">🔄 เปลี่ยน Code ใหม่</button></div><div class="mini muted" style="margin-top:6px">เปลี่ยน Code ใหม่เมื่อ Code เดิมหลุดไปในที่สาธารณะ Code และ QR เดิมจะใช้ไม่ได้ทันที</div></div>
  <br><div class="card" style="box-shadow:none"><b>🎟️ ลิงก์เชิญพิเศษ</b><div class="muted mini">ใช้เข้าร่วมได้ทุกโหมด แม้ตั้งเป็น "เชิญเท่านั้น" กำหนดวันหมดอายุและจำนวนครั้งได้ ยกเลิกได้ทุกเมื่อ</div><div class="row" style="margin-top:8px"><select id="lnkHours" class="sel"><option value="24">หมดอายุใน 1 วัน</option><option value="168" selected>หมดอายุใน 7 วัน</option><option value="720">หมดอายุใน 30 วัน</option><option value="0">ไม่หมดอายุ</option></select><select id="lnkUses" class="sel"><option value="1">ใช้ได้ 1 ครั้ง</option><option value="5">ใช้ได้ 5 ครั้ง</option><option value="20" selected>ใช้ได้ 20 ครั้ง</option><option value="0">ไม่จำกัดครั้ง</option></select><button class="btn sm" onclick="createInviteLink('${type}','${id}')">＋ สร้างลิงก์</button></div><div id="lnkList" style="margin-top:10px"></div></div>`:''}`);
  renderPendingInvites(type,id);renderFriendInviteList(type,id);if(x.isAdmin)renderInviteLinks(type,id)}catch(e){err(e)}}
async function inviteEmail(type,id){const btn=$('invEmailBtn');try{const email=$('invEmail').value.trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error('รูปแบบอีเมลไม่ถูกต้อง');btn.disabled=true;const {data,error}=await sb.rpc('invite_by_email',{p_type:type,p_id:id,p_email:email});if(error)throw error;$('invEmail').value='';toast(data==='duplicate'?'มีคำเชิญถึงอีเมลนี้ค้างอยู่แล้ว':data==='pending_admin'?'ส่งคำเชิญแล้ว รอ Admin อนุมัติ':'ส่งคำเชิญแล้ว');renderPendingInvites(type,id);loadInbox()}catch(e){err(e)}finally{if(btn)btn.disabled=false}}
async function renderPendingInvites(type,id){const box=$('invPending');if(!box)return;try{const {data,error}=await sb.from('invitations').select('*').eq('target_type',type).eq('target_id',id).in('status',['pending_admin','pending_invitee']).order('created_at',{ascending:false});if(error)throw error;const x=inviteTarget(type,id);box.innerHTML=(data||[]).map(i=>`<div class="filerow"><span>✉️ ${esc(i.email)} · <span class="pill ${i.status==='pending_admin'?'private':''}">${i.status==='pending_admin'?'รอ Admin อนุมัติ':'รอผู้ถูกเชิญตอบรับ'}</span></span><div class="spacer"></div>${i.invited_by===currentUser.id||x?.isAdmin?`<button class="btn sm danger" onclick="cancelInvite('${i.id}','${type}','${id}')">ยกเลิก</button>`:''}</div>`).join('')}catch(e){box.innerHTML=''}}
async function cancelInvite(iid,type,id){if(!confirm('ยกเลิกคำเชิญนี้?'))return;try{const {error}=await sb.rpc('cancel_invitation',{p_id:iid});if(error)throw error;renderPendingInvites(type,id);loadInbox()}catch(e){err(e)}}
async function saveJoinPolicy(type,id){const btn=$('polBtn');try{const pol=document.querySelector('input[name="polSel"]:checked')?.value;const pw=$('polPw')?.value||'';if(pol==='password'&&pw&&pw.length<4)throw new Error('รหัสผ่านต้องยาวอย่างน้อย 4 ตัวอักษร');btn.disabled=true;const {error}=await sb.rpc('set_join_policy',{p_type:type,p_id:id,p_policy:pol,p_password:pw||null});if(error)throw error;toast('บันทึกการตั้งค่าแล้ว');await render();openInviteModal(type,id)}catch(e){err(e)}finally{if(btn)btn.disabled=false}}
async function regenCode(type,id){if(!confirm('เปลี่ยน Code ใหม่? Code และ QR เดิมที่แชร์ไปแล้วจะใช้ไม่ได้'))return;try{const {error}=await sb.rpc('regenerate_code',{p_type:type,p_id:id});if(error)throw error;toast('เปลี่ยน Code แล้ว');await render();openInviteModal(type,id)}catch(e){err(e)}}
async function createInviteLink(type,id){try{const {error}=await sb.rpc('create_invite_link',{p_type:type,p_id:id,p_hours:Number($('lnkHours').value),p_max_uses:Number($('lnkUses').value)});if(error)throw error;toast('สร้างลิงก์เชิญแล้ว');renderInviteLinks(type,id,true)}catch(e){err(e)}}
async function renderInviteLinks(type,id,openFirst){const box=$('lnkList');if(!box)return;try{const {data,error}=await sb.from('invite_links').select('*').eq('target_type',type).eq('target_id',id).is('revoked_at',null).order('created_at',{ascending:false});if(error)throw error;const now=Date.now();const x=inviteTarget(type,id);const live=(data||[]).filter(l=>(!l.expires_at||new Date(l.expires_at).getTime()>now)&&(!l.max_uses||l.uses<l.max_uses));box.innerHTML=live.map((l,i)=>{const url=inviteTokenLink(l.token);return `<div class="listitem"><div class="row"><div style="min-width:0;flex:1"><b>🎟️ ลิงก์ #${live.length-i}</b><div class="mini muted">ใช้ไป ${l.uses}${l.max_uses?'/'+l.max_uses:''} ครั้ง · ${l.expires_at?'หมดอายุ '+esc(new Date(l.expires_at).toLocaleString('th-TH')):'ไม่หมดอายุ'}</div></div><button class="btn sm secondary" onclick="this.closest('.listitem').querySelector('.lnkqr').classList.toggle('hide')">QR</button><button class="btn sm danger" onclick="revokeLink('${l.id}','${type}','${id}')">ยกเลิก</button></div><div style="margin-top:6px">${shareButtons(x?.name||'',url,'')}</div><div class="lnkqr qrbox ${openFirst&&i===0?'':'hide'}" style="margin-top:8px">${qrSvg(url)}</div></div>`}).join('')||'<div class="muted mini">ยังไม่มีลิงก์ที่ใช้งานได้</div>'}catch(e){box.innerHTML=`<div class="warnbox">${esc(friendlyError(e))}</div>`}}
async function revokeLink(lid,type,id){if(!confirm('ยกเลิกลิงก์นี้? คนที่ได้ลิงก์ไปแล้วจะใช้ไม่ได้'))return;try{const {error}=await sb.rpc('revoke_invite_link',{p_link_id:lid});if(error)throw error;toast('ยกเลิกลิงก์แล้ว');renderInviteLinks(type,id)}catch(e){err(e)}}

// ---------- เข้าร่วม ----------
async function joinCodeFromInput(){const el=$('joinCode');const code=el.value.trim();if(!code)return alert('กรุณาใส่ Code');try{await joinByCode(code);el.value=''}catch(e){err(e)}}
async function joinByCode(code,pw){code=String(code||'').trim().toUpperCase();if(!code)return;const {data,error}=await sb.rpc('join_by_code',{p_code:code,p_password:pw||null});if(error)throw error;await handleJoinResult(data||{},{code})}
async function joinGroupTrip(tid,pw){try{const t=tripById(tid);const {data,error}=await sb.rpc('join_group_trip',{p_trip_id:tid,p_password:pw||null});if(error)throw error;await handleJoinResult({...(data||{}),type:'trip',id:tid,name:t?`${t.trip_no} · ${t.name}`:''},{tripId:tid})}catch(e){err(e)}}
async function cancelJoinRequest(tid){try{const {error}=await sb.rpc('cancel_join_request',{p_trip_id:tid});if(error)throw error;toast('ยกเลิกคำขอแล้ว');await loadInbox();renderTrips()}catch(e){err(e)}}
function askJoinPassword(r,ctx){modal(`<div class="section"><h3>🔑 ใส่รหัสผ่านเพื่อเข้าร่วม</h3><div class="spacer"></div><button class="btn secondary" onclick="closeModal()">ยกเลิก</button></div><p><b>${esc(r.name||'')}</b></p>${r.status==='wrong_password'?'<div class="warnbox">รหัสผ่านไม่ถูกต้อง (ลองผิดได้ไม่เกิน 5 ครั้งใน 15 นาที)</div>':''}<div class="field"><label>รหัสผ่าน</label><input id="joinPw" type="password" autocomplete="off" onkeydown="if(event.key==='Enter')$('joinPwBtn').click()"></div><button class="btn" id="joinPwBtn">เข้าร่วม</button>`);$('joinPw').focus();$('joinPwBtn').onclick=async()=>{const pw=$('joinPw').value;if(!pw)return;$('joinPwBtn').disabled=true;try{if(ctx.tripId)await joinGroupTrip(ctx.tripId,pw);else await joinByCode(ctx.code,pw)}catch(e){err(e);$('joinPwBtn').disabled=false}}}
async function handleJoinResult(r,ctx){const name=r.name?`"${r.name}"`:'';switch(r.status){
  case 'joined':closeModal();toast(`เข้าร่วม ${name} แล้ว 🎉`);if(r.type==='trip'&&r.id){curTripId=r.id;devViewId=null;saveCurTrip();calInit=false}await render();go(r.type==='trip'?'dashboard':'groups');break;
  case 'already':closeModal();toast('คุณเป็นสมาชิกอยู่แล้ว');if(r.type==='trip'&&r.id)await switchTrip(r.id);break;
  case 'password_required':case 'wrong_password':askJoinPassword(r,ctx);break;
  case 'invite_only':closeModal();alert(`${name} ตั้งเป็น "เชิญเท่านั้น" เข้าร่วมด้วย Code ไม่ได้\nขอลิงก์เชิญหรือคำเชิญจาก Admin`);break;
  case 'not_found':closeModal();alert('ไม่พบ Code นี้ ตรวจสอบตัวอักษรอีกครั้ง (Code อาจถูกเปลี่ยนใหม่แล้ว)');break;
  case 'too_many':closeModal();alert('ลองผิดหลายครั้งเกินไป กรุณารอ 15 นาทีแล้วลองใหม่');break;
  case 'invalid':alert('ลิงก์เชิญไม่ถูกต้อง หรือถูกยกเลิกแล้ว');break;
  case 'expired':alert('ลิงก์เชิญหมดอายุแล้ว กรุณาขอลิงก์ใหม่');break;
  case 'used_up':alert('ลิงก์เชิญนี้ถูกใช้ครบจำนวนแล้ว กรุณาขอลิงก์ใหม่');break;
  case 'request_sent':closeModal();toast('ส่งคำขอเข้าร่วมแล้ว รอ Admin อนุมัติ');await loadInbox();renderTrips();break;
  case 'request_pending':closeModal();alert('ส่งคำขอไปแล้ว กำลังรอ Admin อนุมัติ');break;
  default:alert('ผลลัพธ์ไม่ทราบสถานะ: '+(r.status||'-'))}}

// ---------- ลิงก์ที่เปิดมาจาก QR / แชร์ (?join= หรือ ?invite=) ----------
function capturePendingJoin(){const p=new URLSearchParams(location.search);const j=p.get('join'),i=p.get('invite'),fr=p.get('friend');if(!j&&!i&&!fr)return;try{localStorage.setItem('te_pending_join',JSON.stringify({join:j,invite:i,friend:fr,at:Date.now()}))}catch(_){}history.replaceState(null,'',APP_URL+location.hash)}
function pendingJoin(){try{const x=JSON.parse(localStorage.getItem('te_pending_join')||'null');if(x&&Date.now()-x.at<3*86400000)return x;localStorage.removeItem('te_pending_join')}catch(_){}return null}
function renderAuthInviteBanner(){const el=$('authInvite');if(!el)return;const x=pendingJoin();el.innerHTML=x?`<div class="okbox" style="margin:10px 0">${x.friend?`🤝 มีคนชวนคุณเป็นเพื่อน (Friend Code: <b>${esc(x.friend)}</b>)`:`📨 คุณได้รับคำเชิญ${x.join?` (Code: <b>${esc(x.join)}</b>)`:''}`}<br>เข้าสู่ระบบหรือสมัครสมาชิก แล้วระบบจะพาเข้าร่วมให้อัตโนมัติ</div>`:''}
async function processPendingJoin(){const x=pendingJoin();if(!x)return;try{localStorage.removeItem('te_pending_join')}catch(_){}try{if(x.friend){await sendFriend({p_code:x.friend});go('friends')}else if(x.invite){const {data,error}=await sb.rpc('join_by_invite_link',{p_token:x.invite});if(error)throw error;await handleJoinResult(data||{},{})}else if(x.join)await joinByCode(x.join)}catch(e){err(e)}}

// ---------- 🔔 กล่องแจ้งเตือน ----------
async function loadInbox(){try{const {data,error}=await sb.rpc('my_inbox');if(error)throw error;inbox=data||{invites:[],approvals:[],my_requests:[]}}catch(x){console.warn('inbox',x);inbox={invites:[],approvals:[],my_requests:[]}}renderInboxBadge();if(currentUser&&cache.trips.some(t=>!cache.roles[t.id]))renderTrips()}
function renderInboxBadge(){const n=(inbox.invites?.length||0)+(inbox.approvals?.length||0)+(inbox.friend_requests?.length||0);document.querySelectorAll('.inboxCount').forEach(el=>{el.textContent=n>99?'99+':n;el.classList.toggle('hide',!n)})}
async function openInbox(){await loadInbox();const inv=inbox.invites||[],ap=inbox.approvals||[],frq=inbox.friend_requests||[];const when=d=>esc(new Date(d).toLocaleString('th-TH'));
  modal(`<div class="section"><h3>🔔 การแจ้งเตือน</h3><div class="spacer"></div><button class="btn secondary" onclick="closeModal()">ปิด</button></div>${frq.length?`<h4 style="margin:6px 0">🤝 คำขอเป็นเพื่อน (${frq.length})</h4>${frq.map(f=>`<div class="listitem row"><b style="flex:1">${esc(f.name)}</b><button class="btn sm" onclick="respondFriend('${f.id}',true)">✔ ยอมรับ</button><button class="btn sm secondary" onclick="respondFriend('${f.id}',false)">ปฏิเสธ</button></div>`).join('')}<br>`:''}<h4 style="margin:6px 0">📨 คำเชิญถึงคุณ (${inv.length})</h4>${inv.map(i=>`<div class="listitem"><div><b>${esc(i.target_name||'')}</b> <span class="badge">${i.target_type==='group'?'Group':'Trip'}</span></div><div class="muted mini">เชิญโดย ${esc(i.by_name||'-')} · ${when(i.created_at)}</div><div class="row" style="margin-top:6px"><button class="btn sm" onclick="respondInvite('${i.id}',true)">✔ เข้าร่วม</button><button class="btn sm secondary" onclick="respondInvite('${i.id}',false)">ปฏิเสธ</button></div></div>`).join('')||'<div class="muted mini" style="padding:6px 0">ไม่มีคำเชิญใหม่</div>'}<h4 style="margin:16px 0 6px">🛡️ รอคุณอนุมัติ (${ap.length})</h4>${ap.map(a=>`<div class="listitem"><div><b>${esc(a.person||'')}</b> ${a.kind==='request'?'ขอเข้าร่วม':'ถูกเชิญเข้า'} <b>${esc(a.target_name||'')}</b></div><div class="muted mini">${a.kind==='invitation'?`เชิญโดย ${esc(a.by_name||'-')} · `:''}${when(a.created_at)}</div><div class="row" style="margin-top:6px"><button class="btn sm" onclick="decideApproval('${a.kind}','${a.id}',true)">✔ อนุมัติ</button><button class="btn sm secondary" onclick="decideApproval('${a.kind}','${a.id}',false)">ไม่อนุมัติ</button></div></div>`).join('')||'<div class="muted mini" style="padding:6px 0">ไม่มีรายการรออนุมัติ</div>'}`)}
async function respondInvite(id,accept){try{const {data,error}=await sb.rpc('respond_invitation',{p_id:id,p_accept:accept});if(error)throw error;if(accept)await handleJoinResult(data||{},{});else{toast('ปฏิเสธคำเชิญแล้ว');openInbox()}loadInbox()}catch(e){err(e)}}
async function decideApproval(kind,id,approve){try{const {error}=await sb.rpc(kind==='request'?'decide_join_request':'decide_invitation',{p_id:id,p_approve:approve});if(error)throw error;toast(approve?'อนุมัติแล้ว':'ไม่อนุมัติแล้ว');if(approve&&kind==='request')await render();openInbox()}catch(e){err(e)}}
