// =====================================================================
// summary.js — หน้า "สรุป" (V17): ภาพรวม · รายวัน · หมวดหมู่ · รายการ
// =====================================================================
let sumTab='overview',sumCat='all';
function openSummary(tab,toSettle){sumTab=tab||'overview';go('summary');if(toSettle)setTimeout(()=>$('settlementBox')?.scrollIntoView?.({behavior:'smooth',block:'start'}),250)}
function setSumTab(tab){sumTab=tab;renderSummary()}
function expenseRowHtml(e){const p=cache.members.find(m=>m.id===e.payer_id)||{id:e.payer_id};const rc=receiptsFor(e).length;return `<div class="exprow" onclick="openExpenseItem('${e.id}')">${catIcon(e.category,42)}<div class="exmain"><b>${esc(expName(e))}</b><div class="mini muted">${esc(fmtDate(e.expense_date))}${e.expense_time?' · '+esc(String(e.expense_time).slice(0,5)):''} · ${avatarHtml(p,16)} ${esc(displayName(p))}${rc?` · 📎${rc}`:''}</div></div><div class="exright"><b>${money(netOf(e))}</b>${e.refunded?`<div class="mini okText">↩ ${money(e.refunded)}</div>`:''}${catBadge(e.category)}</div></div>`}
function openExpenseItem(id){const e=cache.expenses.find(x=>x.id===id);if(!e)return;if(canEditRow(e))return editExpense(id);const p=cache.members.find(m=>m.id===e.payer_id)||{id:e.payer_id};const rc=receiptsFor(e);modal(`<div class="sheethead"><h3>${esc(expName(e))}</h3><div class="spacer"></div><button class="btn secondary sm" onclick="closeModal()">ปิด</button></div><div class="row">${catIcon(e.category,48)}<div><div class="bigamt">${money(netOf(e))}</div>${catBadge(e.category)}</div></div><div class="listitem">📅 ${esc(fmtDate(e.expense_date))}${e.expense_time?' '+esc(String(e.expense_time).slice(0,5)):''}</div><div class="listitem row">จ่ายโดย ${avatarHtml(p,22)} <b>${esc(displayName(p))}</b></div>${e.refunded?`<div class="listitem">↩ คืนเงินแล้ว ${money(e.refunded)} (ยอดเต็ม ${money(e.amount)})</div>`:''}${rc.length?`<div class="listitem"><button class="btn sm secondary" onclick="openReceipts('${e.id}')">📎 ดูใบเสร็จ (${rc.length})</button></div>`:''}<div class="mini muted">แก้ไขได้เฉพาะผู้สร้างรายการหรือ Admin</div>`,'sheet')}
function renderSummary(){const box=$('summaryBox');if(!box)return;document.querySelectorAll('#sumTabs button').forEach(b=>b.classList.toggle('active',b.dataset.t===sumTab));const t=curTrip();if(!t){box.innerHTML='<div class="card empty">ยังไม่มี Trip</div>';return}const list=cache.expenses,total=list.reduce((a,e)=>a+netOf(e),0),bs=budgetStats(t.id),parts=catParts(list);
  if(sumTab==='overview'){
    // 1) การ์ดหมวดหมู่ค่าใช้จ่าย (โดนัท) เหมือนหน้าหลัก  2) ยอดจ่ายรวมของแต่ละคน (ก่อนหักคืน)  3) รายการที่ต้องชำระคืน (หลังหักคืน)
    const paid={};cache.expenses.forEach(e=>{paid[e.payer_id]=(paid[e.payer_id]||0)+Number(e.amount||0)});
    const ids=[...new Set([...cache.tripMembers.map(m=>m.user_id),...Object.keys(paid)])].sort((x,y)=>(paid[y]||0)-(paid[x]||0));
    box.innerHTML=`${categoryDonutCard(list,"setSumTab('category')")}<div class="card"><div class="section"><div><h3>ยอดจ่ายรวมของแต่ละคน</h3><div class="muted mini">ก่อนหักเงินคืน</div></div></div>${ids.map(id=>{const p=cache.members.find(m=>m.id===id)||{id};const v=paid[id]||0;return `<div class="listitem row memtap" style="flex-wrap:nowrap" onclick="openMemberProfile('${id}')">${avatarHtml(p,32)}<b style="flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis">${esc(displayName(p))}</b><b class="${v?'':'muted'}">${money(v)}</b></div>`}).join('')||'<div class="empty">ยังไม่มีข้อมูล</div>'}<div class="listitem row" style="flex-wrap:nowrap;border-top:2px solid var(--line)"><b style="flex:1">รวมทั้งหมด</b><b>${money(grossTotal(list))}</b></div></div><div class="card hero" id="settleCard"><div class="section"><div><h3>รายการที่ต้องชำระคืน</h3><div class="muted mini">หลังหักเงินคืนแล้ว</div></div></div><div id="settlementBox"></div></div>`;renderSettlement(t.id,'settlementBox')}
  else if(sumTab==='daily'){const days=tripDates(t);const by={};list.forEach(e=>{const k=t.start_date&&e.expense_date<t.start_date?'pre':e.expense_date;by[k]=(by[k]||0)+netOf(e)});const keys=[...(by.pre?['pre']:[]),...(days.length?days:Object.keys(by).filter(k=>k!=='pre').sort()),...Object.keys(by).filter(k=>k!=='pre'&&days.length&&!days.includes(k)).sort()];const mx=Math.max(1,...keys.map(k=>by[k]||0));box.innerHTML=`<div class="card"><div class="section"><h3>ค่าใช้จ่ายรายวัน</h3></div>${keys.length?`<div class="bars">${keys.map(k=>`<div class="bar" onclick="document.getElementById('d-${k}')?.scrollIntoView?.({behavior:'smooth'})"><span class="bv">${by[k]?moneyShort(by[k]):''}</span><i style="height:${Math.max(2,(by[k]||0)/mx*100)}%"></i><small>${k==='pre'?'จอง':new Date(k+'T00:00:00').getDate()}</small></div>`).join('')}</div><div class="mini muted" style="text-align:center">${esc(fmtRange(t))}${by.pre?' · "จอง" = ค่าใช้จ่ายก่อนวันเดินทาง':''}</div>`:'<div class="empty">ยังไม่มีข้อมูล</div>'}</div>${keys.filter(k=>by[k]).map(k=>{const items=list.filter(e=>(k==='pre'?t.start_date&&e.expense_date<t.start_date:e.expense_date===k));return `<br><div class="card" id="d-${k}"><div class="section"><h3>${k==='pre'?'ก่อนเดินทาง (ค่าจองล่วงหน้า)':esc(thaiDate(k))}</h3><div class="spacer"></div><b>${money(by[k])}</b></div>${items.map(expenseRowHtml).join('')}</div>`}).join('')}`}
  else if(sumTab==='category'){const gt=grossTotal(list);box.innerHTML=`${categoryDonutCard(list,null)}<div class="card"><div class="section"><div><h3>ยอดรวมตามหมวดหมู่</h3><div class="muted mini">ก่อนหักเงินคืน</div></div><div class="spacer"></div><b>${money(gt)}</b></div>${parts.map(p=>catLine(p,gt,true)).join('')||'<div class="empty">ยังไม่มีข้อมูล</div>'}</div>`}
  else{const cats=catParts(list);const q=($('sumSearch')?.value||'');box.innerHTML=`<div class="searchbox"><span>🔍</span><input id="sumSearch" placeholder="ค้นหารายการ..." value="${esc(q)}" oninput="renderSumList()"></div><div class="pills"><button class="${sumCat==='all'?'on':''}" onclick="sumCat='all';renderSummary()">ทั้งหมด</button>${cats.map(c=>`<button class="${sumCat===c.k?'on':''}" style="--c:${c.color}" onclick="sumCat='${esc(c.k).replace(/'/g,'&#39;')}';renderSummary()">${catIcon(c.k,20)}<span>${esc(c.name)}</span></button>`).join('')}</div><div class="row filterbar" style="margin:8px 0"><select id="expSortKey" onchange="setExpSortKey(this.value)"><option value="date">เรียงตาม: วันที่</option><option value="amount">เรียงตาม: จำนวนเงิน</option><option value="detail">เรียงตาม: รายการ</option><option value="payer">เรียงตาม: ผู้จ่าย</option><option value="receipts">เรียงตาม: ใบเสร็จ</option></select><button class="btn sm secondary" id="expSortDir" onclick="toggleExpSortDir()"></button><div class="spacer"></div><button class="btn sm w" onclick="openExpenseForm()">＋ เพิ่ม</button></div><div class="card" id="sumList"></div>`;renderSumList()}
  hydrateMedia(box)}
function catLine(p,total,withCount){const n=cache.expenses.filter(e=>(e.category||'other')===p.k).length;return `<div class="catline" onclick="sumCat='${esc(p.k).replace(/'/g,'&#39;')}';setSumTab('list')">${catIcon(p.k,36)}<div style="flex:1;min-width:0"><div class="row" style="flex-wrap:nowrap"><b style="flex:1">${esc(p.name)}</b><b>${money(p.v)}</b></div><div class="row" style="flex-wrap:nowrap;gap:8px"><div class="summarybar" style="flex:1;height:6px"><i style="width:${total?p.v/total*100:0}%;background:${p.color}"></i></div><span class="mini muted">${total?Math.round(p.v/total*100):0}%${withCount?` · ${n} รายการ`:''}</span></div></div></div>`}
function renderSumList(){const box=$('sumList');if(!box)return;const k=expSort.key==='trip'||expSort.key==='category'?'date':expSort.key,dir=expSort.dir==='asc'?1:-1;const list=filteredExpenses().filter(e=>sumCat==='all'||(e.category||'other')===sumCat).map(e=>({e,v:expSortValue(e,k)})).sort((a,b)=>(typeof a.v==='number'?a.v-b.v:String(a.v).localeCompare(String(b.v),'th'))*dir).map(x=>x.e);if($('expSortKey'))$('expSortKey').value=k;if($('expSortDir'))$('expSortDir').textContent=sortDirLabel();const sum=list.reduce((a,e)=>a+netOf(e),0);box.innerHTML=(list.map(expenseRowHtml).join('')||'<div class="empty">ไม่พบรายการ</div>')+(list.length?`<div class="row" style="padding-top:10px"><span class="muted">${list.length} รายการ</span><div class="spacer"></div><b>${money(sum)}</b></div>`:'');hydrateMedia(box)}
